### ISSUE TITLE
i18n link transform

### ISSUE THREAD

**Issue by dreitzner** [sveltejs/vite-plugin-svelte#100]
### Describe the problem

I'm currently working on i18n for SvelteKit.
One of the last hurdles would be to enable a language prefix for internal links.

Issue: https://github.com/sveltejs/kit/issues/553
Draft PR: https://github.com/sveltejs/kit/pull/1810

### Describe the proposed solution

Add an option for i18n where the language of the current context can be passed to.
This in turn will prefix internal urls (from the html part) with the defined language prefix (eg. 'en', 'de', 'fr',...)
The language prefix is already accessible in most of SvelteKit use cases inside of it

### Alternatives considered

I'll not sure if there are any intelligent ones... 

### Importance

would make my life easier

**Comment by dominikg** [comment]
Hi, thank you for reaching out and looking into i18n

There is no compiler option for a language prefix and vite-plugin-svelte has no knowledge/concept of any routing nor manipulates components on it's own. (besides some small dev-only things to improve dx)

Please elaborate a bit why this is something that should be handled by vite-plugin-svelte and what exactly you want it to do.

An alternative could be to use a markup preprocessor to find links and update them accordingly. This can be added through svelte.config.js without having to change vite-plugin-svelte itself.

note: 
i18n for sveltekit is still in draft, see also this issue: https://github.com/sveltejs/kit/issues/1274  (warning, also very long and some overlap with 553), so if there is something that vite-plugin-svelte can do to showcase your draft, it would end up in the recently added "experimental" section of the options until there is a finalized RFC for i18n that describes it in more detail.

**Comment by dreitzner** [comment]
@dominikg thank you for your quick answer :)

### The problem:
- any `<a href="/internal/route">click me</a>` will not change when i18n changes
- if we would do that through the router, we run into the problem of users trying to open links in new tabs
- svelte kit does not really compile the code itself, so doing a transform after the fact gets way to complicated in my opinion

#### My though process:
1. sveltekit knows the current selected language
2. we also know about internal links
3. it should be "easy" to transform those at build time
4. as we hand the build of to vite => vite svelte plugin => svelte it sounds very conveniant to go down that route (pun intended)

### Example
`
// IN
// file:
<script><script>
<a href="/blog">BLOG</a>

// options:
{
  lang: 'de'
}

// OUT
// file:
<script><script>
<a href="/de/blog">BLOG</a>
`

Maybe we need a add a special attribute to the `<a>` tag, but I would love for it to work without it if possible (bugs and such)

I also want to prevent going down the road of using `<Link>` instead of `<a>` 😨

**Comment by dominikg** [comment]
I believe this can and should be handled within sveltekit itself.

Static compile-time replacement like the one you outlined above could be done with a markup [preprocessor](https://svelte.dev/docs#svelte_preprocess). But how would that work with clientside routing when the user selects a different language?

Maybe some form of active href building ala `<a href={i18nRoute('/blog')}>`  could work better? 

I'm going to close this enhancement request as out-of-scope for vite-plugin-svelte, but it's great to see you getting the ball rolling for i18n in sveltekit and would be happy to discuss this further on [discord](https://svelte.dev/chat).

**Comment by dreitzner** [comment]
@dominikg  thank you!

I am a fan of `i18nRoute`
