### ISSUE TITLE
Readonly fields not exposed from classes in vite-plugin-svelte 4.0.0

### ISSUE THREAD

**Issue by delphiak** [sveltejs/vite-plugin-svelte#1006]
### Describe the bug

With 3.1.2 version on vite-plugin-svelte  I was able to use on UI readonly fields from my classes that were $state() runes in top components. In 4.0.0 version that seems not longer be possible and I have to manually implement copying values an exposing them.
Svelte itself version seems to be irrelevant as I've tested every four scenarios with Svelte 5.0.0-next.164 and 5.0.5 and it either works well on 3.1.2 version of plugin or does not work at all with 4.0.0 on both Svelte versions.

Was this by design or some issue with latest release? The lack of simple usage of readonly fields makes up for a lot of clutter in the components so it is not ideal

### Reproduction URL

https://stackblitz.com/edit/vitejs-vite-gvt3dj?file=src%2FApp.svelte,package.json&terminal=dev

### Reproduction

Running code from reproduction URL on @sveltejs/vite-plugin-svelte 4.0.0 fails to run with class with readonly fields.
Running same code with 3.1.2 runs as expected.

When changing usage from `UserReadonlyClass` to `UserRegularClass` the behavior is as expected, but additional clutter in code is definitely a burden as I would have to manually expose all the variables to have types working nicely in Typescript

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 4.0.0 
    svelte: ^5.0.3 => 5.0.5 
    vite: ^5.4.9 => 5.4.10
```

**Comment by dominikg** [comment]
https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md#vitepreprocess

you have to explicitly enable script preprocessing to use typescript features that generate code in .svelte script blocks since 4.0 because svelte5 does not support it.

but i'd recommend moving the class to a separate .ts file and importing it instead.

**Comment by delphiak** [comment]
Thanks, it works indeed :)
