### ISSUE TITLE
add link to new warningFilter option in onwarn docs

### ISSUE THREAD

**Issue by ptrxyz** [sveltejs/vite-plugin-svelte#1016]
### Describe the bug

I wanted to use https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#onwarn yet it seems this is now superseeded by Svelte 5's `warningFilter` compiler option.

I propose to update the docs accordingly or include a link to the new option?

### Reproduction URL

-

### System Info

```shell
-
```

**Comment by ptrxyz** [comment]
For reference: https://svelte.dev/docs/svelte/svelte-compiler#ModuleCompileOptions

**Comment by dominikg** [comment]
onwarn is still supported. warningFilter is less flexible and does not include warnings emitted by vite-plugin-svelte (something we could change for uniformity)

a link to the new option can be added to the docs here, PR welcome.

**Comment by dominikg** [comment]
thank you!
