### ISSUE TITLE
svelte 5 compatibility mode, Unexpected token [plugin vite-plugin-svelte:optimize-svelte]

### ISSUE THREAD

**Issue by olivierchatry** [sveltejs/vite-plugin-svelte#1021]
### Describe the bug

So I'm not to sure how to describe it, as sometimes builds is working, on sometime it fails. I'm getting :

```
✘ [ERROR] node_modules/svelte-splitpanes/dist/Splitpanes.svelte:29:7 Unexpected token [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/svelte-splitpanes/dist/Splitpanes.svelte:29:7:
      29 │ mport GatheringRound from './internal/GatheringRound.svelte';
         ╵        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/svelte-splitpanes/dist/index.js:1:38:
      1 │ export { default as Splitpanes } from './Splitpanes.svelte';
        ╵                                       ~~~~~~~~~~~~~~~~~~~~~
```

While building one of my software. I'm using a mono-repo, with a common library shared accross all the software. The exact same code will be building on one application, and fails on another with this error. I have tried to make a repro case, but failed to do so. If anyone as any pointers on what I'm doing wrong.

### Reproduction URL

https://stackblitz.com/edit/vitejs-vite-4nnsuk?file=index.html&terminal=dev

### Reproduction

( the repro link contains nothing ).

### System Info

```shell
System:
    OS: Linux 6.11 Fedora Linux 41 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 9 7940HS w/ Radeon 780M Graphics
    Memory: 49.65 GB / 62.02 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
  Browsers:
    Chrome: 130.0.6723.116
  npmPackages:
    @sveltejs/pancake: github:XvisionAS/pancake => 0.0.17 
    @sveltejs/vite-plugin-svelte: ~4.0.0 => 4.0.0 
    svelte: ~5.1.12 => 5.1.15 
    vite: ~5.4.10 => 5.4.11
```

**Comment by dominikg** [comment]
the link provided in the reproduction does not contain the dependency `svelte-splitpanes` mentioned in the error message. The error itself seems to happen during dependency optimization. I'd recommend deleting node_modules and reinstalling in case something broke it.

For further investigation we require a reproduction with steps how to create this situation reliably.

**Comment by olivierchatry** [comment]
Tries everything ( removing node_modules, removing package-lock.json, etc. ) nothing is working and still have the same issue. I will try to find a repro case but I'm not sure it will be easy.

**Comment by olivierchatry** [comment]
Yup, it's definitly a build caching issue. I'm usng tilt, switching branch from svelte 4 to 5 lead to this error. Clean build make it go away. Weird, will try to find where it come on my setup. Many thanks !

**Comment by olivierchatry** [comment]
Well, it's back with a vengeance. Now on a clean cluster ( delete and recreated minikube cluster ) I get the same error. Still not sure how to repro it.

**Comment by olivierchatry** [comment]
Sorry, I did not update the bugs, but we found the issue was using `--legacy-peer-deps` when installing package on a local package that is use on the software. Do not ask me why, but removing this made this error go away.

**Comment by eranknafo2001** [comment]
removing the lock file solved it
