### ISSUE TITLE
Vite 6.0.1 fails with this plugin

### ISSUE THREAD

**Issue by go-aegian** [sveltejs/vite-plugin-svelte#1040]
### Describe the bug

npm error Found: vite@6.0.1
npm error node_modules/vite
npm error   dev vite@"6.0.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer vite@"^5.0.0" from @sveltejs/vite-plugin-svelte@4.0.2
npm error node_modules/@sveltejs/vite-plugin-svelte
npm error   peer @sveltejs/vite-plugin-svelte@"^3.0.0 || ^4.0.0-next.1" from @sveltejs/kit@2.8.5
npm error   node_modules/@sveltejs/kit
npm error     dev @sveltejs/kit@"2.8.5" from the root project
npm error     1 more (@sveltejs/adapter-static)

### Reproduction URL

none

### System Info

```shell
vite 6.0.1
```

**Comment by dominikg** [comment]
you have to use vite-plugin-svelte@5 with vite@6

please be aware that sveltekit official support for vite6 is still pending (should be released soon), so until that has happened you are going to get peer dependency warnings, use at your own risk.
