### ISSUE TITLE
Replace querystring with URLSearchParams

### ISSUE THREAD

**Issue by benmccann** [sveltejs/vite-plugin-svelte#106]
### Describe the problem

It is recommended to avoid using querystring. I'm getting a warning when building SvelteKit about querystring and can't figure out where it's coming from. This is one of a couple libraries that use it. I'm hoping if we can remove it then I won't get the warning anymore

https://github.com/sveltejs/vite-plugin-svelte/blob/d1d2638b247830852faa89e7b9bc9a430b81ba51/packages/vite-plugin-svelte/src/utils/id.ts#L2

### Describe the proposed solution

Use URLSearchParams instead

### Alternatives considered

status quo

### Importance

nice to have

**Comment by dominikg** [comment]
looks like querystring was deprecated. it's been used because vite uses it too: https://github.com/vitejs/vite/search?q=querystring&type=code 

because vite bundles it, there won't be any warnings from there tho.
