### ISSUE TITLE
Improve handling of compilerOptions.hydratable

### ISSUE THREAD

**Issue by dominikg** [sveltejs/vite-plugin-svelte#120]
### Describe the problem

Currently vite-plugin-svelte defaults  to `hydratable: true` which is not the default for svelte and mostly due to the reason that it reliably works with and without ssr.

In situations where you don't use ssr and/or don't need clientside hydration, this leads to increased output size.

### Describe the proposed solution

Only compile with `hydratable: true` when one of the following is true

* compilerOptions.hydratable is set to true in svelte config
* compilerOptions.hydratable is not defined in svelte config and viteConfig.ssr exists 

### Alternatives considered

stick with the current default. Users that want `hydratable: false` should set it in svelte config.

### Importance

nice to have

**Comment by benmccann** [comment]
Sounds fine to me as long as we specify a default of true in SvelteKit still

**Comment by dominikg** [comment]
Explicit compilerOptions.hydratable in kit is a good idea if #121 doesn't work out. 

It would work even with the current version of kit as it sets `viteConfig.ssr`.

That check isn't ideal (false positive if the config value is set but ssr isn't used), but the more correct/strict check
```js
const isSSR = !!(viteEnv.command === 'serve' ? viteConfig.server.middlewareMode : viteConfig.build.ssr);
``` 
 would be false for the build of client bundle, where hydratable is needed.

**Comment by bluwy** [comment]
I never realized `hydratable` was set to `true` by default all these time. Is it true for production builds too? I think this is a welcomed change.

**Comment by dominikg** [comment]
PR in kit to set hydratable: https://github.com/sveltejs/kit/pull/2024

using viteConfig.ssr turned out to be not the best idea as this is not always set when hydratable is needed. So instead of adding an automatic default that only works half of the time, vite-plugin-svelte will default to `hydratable: false` always

**Comment by dominikg** [comment]
released https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/CHANGELOG.md#100-next15
