### ISSUE TITLE
vite-plugin-svelte 1.0.0-next.23 breaks the ssr with svelte-i18n

### ISSUE THREAD

**Issue by livehtml** [sveltejs/vite-plugin-svelte#168]
### Describe the bug

When I update my SvelteKit App to vite-plugin-svelte 1.0.0-next.23 it will cause error:
```
9:44:24 PM [vite] Error when evaluating SSR module /node_modules/.pnpm/svelte-i18n@3.3.10_svelte@3.42.4/node_modules/svelte-i18n/dist/runtime.esm.js:
SyntaxError: Illegal property in declaration context
    at new AsyncFunction (<anonymous>)
    at instantiateModule (/home/www/sources/node_modules/.pnpm/vite@2.5.6/node_modules/vite/dist/node/chunks/dep-9f74b403.js:75099:28)
```

Only revert back to 1.0.0-next.22 of this module makes everything works again.

### Reproduction

Use svelte-i18n with SSR.

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (2) x64 DO-Regular
    Memory: 291.61 MB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.6 - /usr/bin/node
    npm: 6.14.15 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.46 => 1.0.0-next.46 
    @sveltejs/adapter-static: ^1.0.0-next.18 => 1.0.0-next.18 
    @sveltejs/kit: next => 1.0.0-next.166 
    svelte: ^3.42.5 => 3.42.5
```

### Severity

blocking all usage of vite-plugin-svelte

**Comment by brev** [comment]
Thanks @livehtml, this just popped up for me last night, and I could not figure it out. Whew.

**Comment by bluwy** [comment]
Related: https://github.com/sveltejs/kit/issues/2418

The reason for this issue was that 23 adds normal svelte libraries to `ssr.noExternal` too in order to support `svelte/ssr`. This error should only happen in dev mode, but we weren't doing `svelte/ssr` resolving in dev mode either, so there isn't any reason for the `ssr.noExternal` thing. It was an oversight on my part, cooking up a PR.

**Comment by bluwy** [comment]
As for the actual error `SyntaxError: Illegal property in declaration context`, I can't pinpoint why that happens. Vite's stack trace rewrite must've not captured something. But with the PR, it should also give a performance boost in dev mode too besides working around the error.

**Comment by livehtml** [comment]
@brev @bluwy thanks guys for answers.

I've found another workaround: add `config.kit.vite.ssr.external = ['svelte-i18n'];` to the svelte.config.js and it works now with vite-plugin-svelte 1.0.0-next.23.

May be it helps you.
Unfortunately I personally don't understand what happens here and why it helps :-)

**Comment by bluwy** [comment]
yeah the `ssr.external` workaround is good too if `svelte-i18n` doesn't use any lifecycle functions from `svelte` (I don't think it does). But nonetheless 1.0.0-next.24 should fix this without the workaround now.
