### ISSUE TITLE
Can't get working with Svelte Devtools in Chrome

### ISSUE THREAD

**Issue by mattfysh** [sveltejs/vite-plugin-svelte#174]
### Describe the bug

I've set `compilerOptions.dev` to true, but it's still not connecting to Svelte Devtools in Chrome

### Reproduction

```js
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte({
    compilerOptions: {
      dev: true
    }
  })]
})

```

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 4.13 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 93.0.4577.82
    Safari: 15.0
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.11 => 1.0.0-next.24 
    svelte: ^3.37.0 => 3.42.6 
    vite: ^2.5.4 => 2.5.10
```

### Severity

annoyance

**Comment by mattfysh** [comment]
Tried a few more config options and it still doesn't work. I also can't get Vite to output any log messages either:

```js
export default defineConfig({
  mode: 'development',
  plugins: [svelte({
    compilerOptions: {
      dev: true
    }
  })],
  define: {
    'process.env.NODE_ENV': '"development"',
    'process.env.DEBUG': '"true"',
  },
  logLevel: 'info',
  clearScreen: false,
})
```

**Comment by dominikg** [comment]
To output debug logs with vite, use `DEBUG="vite:*" npm run dev` or `vite --debug`.
You don't have to set `dev: true`, manually in svelte config, vite-plugin-svelte automatically handles this value for you.
It is always true for development and false for production.

For me svelte devtools work on a fresh vite svelte app 

```bash
npm init vite@latest -t svelte vite-svelte-app
cd vite-svelte-app
npm i
```

`npm run dev` opens a server on port 3000, svelte devtools work when inspecting in chrome.

For build you have to set vite mode to "development":

vite.config.js
```js
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte()],
  mode:'development'
})
```
 `npm run build && npm run preview` opens a server on port 5000, svelte devtools work when inspecting in chrome.

:exclamation: do not use development mode builds for production deployments

If this does not work for you please share a repository and step-by-step instructions how to reproduce the error you're seeing. Including details about what is or is not happening, eg stacktraces. ( svelte devtools version etc)

**Comment by mattfysh** [comment]
Thanks for the quick reply @dominikg - I reinstalled the Chrome extension and that appears to have it fixed it. Cheers!

**Comment by ghacosta** [comment]
**not working** on "svelte": "^3.52.0", with Google Chrome Version 107.0.5304.87 (Official Build) (x86_64)


tried adding mode: "development" 
```
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte()],
  mode:'development'
})
```

also tried with inspector enabled as specified here: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#inspector

and finally tried running vite as `vite --debug` but didn't work either.
