### ISSUE TITLE
CSS source maps

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/vite-plugin-svelte#178]
### Describe the problem

I'm not getting CSS source maps when using vite-plugin-svelte for Sass. I believe Vite supports CSS source maps now (https://github.com/vitejs/vite/issues/649), so I'm guessing it's vite-plugin-svelte that doesn't support it?

### Describe the proposed solution

Sass/CSS source map support

### Alternatives considered

Giving up

### Importance

would make my life easier

**Comment by bluwy** [comment]
The PR https://github.com/vitejs/vite/pull/4880 that fixes   https://github.com/vitejs/vite/issues/649 has been reverted in https://github.com/vitejs/vite/pull/4951 as it causes issues in other toolchains. The actual fix lives at https://github.com/vitejs/vite/pull/4950, until that's merge, CSS sourcemaps will then work.

With that said, `vite-plugin-svelte` already handles sourcemaps well, so we'd need to wait for upstream.

**Comment by probablykasper** [comment]
Aah, makes sense

**Comment by bluwy** [comment]
Since css sourcemaps is a general issue in Vite, I'm closing this in favour of https://github.com/vitejs/vite/issues/2830.
