### ISSUE TITLE
use logger provided by vite

### ISSUE THREAD

**Issue by dominikg** [sveltejs/vite-plugin-svelte#19]
**Describe the feature**
vite exposes a logger for plugins, use it

**A Usecase**
* ensures consistency in logging experience within the vite ecosystem
* reduces amount of depencencies

**Alternatives**
keep current logger

**Additional context**
see discussions in https://github.com/sveltejs/vite-plugin-svelte/pull/16

**Comment by dominikg** [comment]
also see https://github.com/vitejs/vite/pull/2521

**Comment by dominikg** [comment]
The current vite logger does not have the features required.
1) no debug level
2) no custom/automatic plugin prefix
3) no payload

may revisit at a later date

**Comment by stingalleman** [comment]
> also see [vitejs/vite#2521](https://github.com/vitejs/vite/pull/2521)

just FYI @dominikg this PR got merged

**Comment by dominikg** [comment]
Thanks for letting me know.
Unfortunately for the reasons outlined above the current logger api isn't suitable for vite-plugin-svelte
