### ISSUE TITLE
vitePluginWasmPack is not a function

### ISSUE THREAD

**Issue by Addeuz** [sveltejs/vite-plugin-svelte#214]
### Describe the bug

I'm trying to use this vite plugin: https://github.com/nshen/vite-plugin-wasm-pack/

But when I put this in my `svelte.config.js` file:
```javascript
import vitePluginWasmPack from 'vite-plugin-wasm-pack';

const config = {
  ...,
  vite: {
    ...,
    plugins: [vitePluginWasmPack('../path/to/my/crate')]
  }
}
```

I get this error: `vitePluginWasmPack is not a function`. It shows in as an error in my svelte files and when running `npm run dev`...

### Reproduction

It can be reproduced by doing this:
```bash
npm init svelte@next my-app
cd my-app
npm install
npm install vite-plugin-wasm-pack --save-dev
```
Then changing `svelte.config.js` to:
```javascript
import preprocess from 'svelte-preprocess';
import vitePluginWasmPack from 'vite-plugin-wasm-pack';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		vite: {
			plugins: [
				vitePluginWasmPack('/home/andreas/gitrepos/dfmain/libraries/audit/public/sie_parser_wasm')
			]
		}
	}
};

export default config;

```

Then running `npm run dev`

### Logs

```shell
vitePluginWasmPack is not a function
TypeError: wasmPack is not a function
    at file:///home/andreas/gitrepos/dfmain/audit/svelte.config.js:35:17
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async load_config (file:///home/andreas/gitrepos/dfmain/audit/node_modules/@sveltejs/kit/dist/cli.js:697:17)
    at async get_config (file:///home/andreas/gitrepos/dfmain/audit/node_modules/@sveltejs/kit/dist/cli.js:769:10)
    at async file:///home/andreas/gitrepos/dfmain/audit/node_modules/@sveltejs/kit/dist/cli.js:831:18
```

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 432.34 MB / 31.29 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.9.1 - /usr/bin/node
    npm: 7.21.1 - /usr/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 94.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.18 => 1.0.0-next.20 
    @sveltejs/kit: ^1.0.0-next.1 => 1.0.0-next.180 
    svelte: ^3.34.0 => 3.43.1
```

### Severity

annoyance

**Comment by bluwy** [comment]
Try `vitePluginWasmPack.default('../path/to/my/crate')` instead. This is due to how the plugin is bundled that's meant for bundler usage, but for node it resolves differently. I'd open an issue in the repo and see if they can do a node-friendly export.

**Comment by Addeuz** [comment]
The workaround worked! So I'm closing the issue. Will open an issue about maybe updating the documentation. If there isn't a major advantage of using a node-friendly export instead of .default

**Comment by nshen** [comment]
hi @bluwy could you tell me how to make a package node friendly ? I am using typescript . Do I need to compile to commonjs ? or what should I do.

**Comment by bluwy** [comment]
@nshen It looks like `vite-plugin-wasm-pack` is publishing commonjs code only at the moment. For CJS, make sure the bundle code is something like this:

```js
module.export = function vitePluginWasmPack() {}
```

not:

```js
module.export.default = function vitePluginWasmPack() {}
```

I'm not sure if there's a way to configure it from `tsc`, but if not a hack [like this](https://github.com/bluwy/vite-plugin-iso-import/blob/ea833710b0c932bb97c1048ec6b5d9d7612e057c/src/index.js#L149-L150) would work too.


---
But issue aside, exporting an ESM version of your code would also be nice, Though a bit tricky with `tsc`, rollup maybe easier to do so.

**Comment by nshen** [comment]
Thanks so much, @bluwy , I add an ESM version and tried to [fix it](https://github.com/nshen/vite-plugin-wasm-pack/commit/3b4d46725d9f248837d9c7eb0c6f38a9bf552eba) , not sure if it works in your case @Addeuz , please try, thanks.
