### ISSUE TITLE
module="context" block cannot have an export matching anything in the regular script block

### ISSUE THREAD

**Issue by arackaf** [sveltejs/vite-plugin-svelte#217]
### Describe the bug

Somewhat similar to https://github.com/sveltejs/vite-plugin-svelte/issues/134

A Svelte module cannot have an export in a module script block with a name matching an export in the regular script block.

Except this breaks even with HMR turned off. 

### Reproduction

See svelte-loadable, in particular the two exported load functions. 

https://github.com/kaisermann/svelte-loadable/blob/master/Loadable.svelte

### Logs

```shell
n/a
```

### System Info

```shell
n/a
```

### Severity

blocking all usage of vite-plugin-svelte

**Comment by dominikg** [comment]
Hi, 

please provide a repo with a reproduction, error logs and system information requested.

Thank you!

**Comment by dominikg** [comment]
looks like this may be fixed in 2.7 by https://github.com/vitejs/vite/pull/5464

**Comment by arackaf** [comment]
@dominikg sorry about that. Is there some sort of online repl in which I can make a repro for a Vite build? It does definitely look like Vite 2.7 fixes this, but if not, I'd be happy to build a simple repro for you.

Also what "logs" are you looking for? Just the error message that gets thrown?

**Comment by dominikg** [comment]
thrown errors, devserver or build log, versions used etc. online there are stackblitz shortcuts https://vite.new/svelte for a vanilla vite+svelte setup or https://node.new/sveltekit for kit.

**Comment by arackaf** [comment]
@dominikg ok cool. Let's wait for Vite 2.7 to drop, and if this isn't fixed for free, I'll get you a proper repro :-)

Thanks for replying!!!

**Comment by bluwy** [comment]
@arackaf Vite 2.7 has been released. Can you confirm this still happens?

**Comment by arackaf** [comment]
@bluwy ya will do!

**Comment by arackaf** [comment]
@bluwy I'll be honest, I can't even repro this with 2.6 anymore, but yeah, it works with 2.7 too. 

Thanks!
