### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by benmccann** [sveltejs/vite-plugin-svelte#218]
### Describe the problem

This calls `compile`:

https://github.com/sveltejs/vite-plugin-svelte/blob/031bbda88a05bdd7e9992c6213f51af70a9ccfd3/packages/vite-plugin-svelte/src/utils/compile.ts#L61

But that doesn't give enough details when there's a parse error

It looks like the same issue exists elsewhere - e.g. `esbuild.ts`

### Describe the proposed solution

I think we need to wrap in a `try` / `catch` and report the `err.frame`

### Alternatives considered

Maybe Svelte itself could give a better error message rather than making the client do it? I've fixed this same issue a whole bunch of places already. But then the client would have less control over display and we'd have to go and update all the clients that already handle the frame

### Importance

would make my life easier

**Comment by benmccann** [comment]
I encountered this trying to use `svelte-repl` `0.4.0` in `svelte.dev`. I modified `vite-plugin-svelte` locally to print the frame before rethrowing the error and found the cause: https://github.com/sveltejs/svelte-repl/pull/188

**Comment by dominikg** [comment]
vite contains code to present errors to the user already. on dev, it does show an overlay on the webpage, on build it prints to console. 

The information of the current error isn't helpful to locate the code causing it. To change that, we have to convert the error thrown by compile to a RollupError and omit the stack.

If we also want to log the error to console on dev, we have to do that ourselves as vite doesn't do it - at least from my initial testing.
