### ISSUE TITLE
Run production builds for non "production" mode

### ISSUE THREAD

**Issue by bluwy** [sveltejs/vite-plugin-svelte#228]
### Describe the bug

When the build `mode` is not "production", vite-plugin-svelte assumes that it is not a production build, so it produces a dev build, which leads to a large bundle size (among other things).

This was raise by @antony on Discord. The current workaround is to have this in the svelte config:

```
const isDevelopmentMode = process.env.NODE_ENV === 'development'
  compilerOptions: {
    dev: isDevelopmentMode
  },
  hot: isDevelopmentMode,
  vite: {
    mode: process.env.NODE_ENV
  }
```

### Reproduction

https://github.com/sveltejs/vite-plugin-svelte/blob/3a38b7732f696b78c1b987dcbea6e52eee75920c/packages/vite-plugin-svelte/src/utils/options.ts#L139

We shouldn't be checking the env mode as `production` here

### System Info

```shell
Not related.
```

### Severity

annoyance

**Comment by antony** [comment]
You have to pass 'hot: false' too otherwise it turns dev mode back on.
