### ISSUE TITLE
migrate tests to vitest

### ISSUE THREAD

**Issue by dominikg** [sveltejs/vite-plugin-svelte#230]
### Describe the problem

Jest esm support is not great, it is bloaty. We mostly stuck to it for a lack of better alternatives

### Describe the proposed solution

Use vitest.dev instead. It is developing at great pace and tied to vite so should be a natural fit. It has a lot of jest like features and more.

### Alternatives considered

uvu, while great for small libraries would require signidicant custom code to rebuild jest features our tests use.

### Importance

would make my life easier

**Comment by mcmxcdev** [comment]
It looks like this issue should be closed since https://github.com/sveltejs/vite-plugin-svelte/pull/337 was merged.

**Comment by dominikg** [comment]
Indeed
