### ISSUE TITLE
`Internal server error:  Cannot read property 'index' of undefined` with no stack trace

### ISSUE THREAD

**Issue by sw-yx** [sveltejs/vite-plugin-svelte#243]
### Describe the bug

in sveltekit, when i make a page that is like:

```html
<script context="module">
	import { REPO_URL } from '../../siteConfig';
	export async function load() {
		return {
			props: {
				REPO_URL
			}
		};
	}
</script>
<script>
	let REPO_URL
  // ... etc
</script>
```

I'm getting this weird error, with no stack trace so i cannot debug it:
![image](https://user-images.githubusercontent.com/6764957/147857340-ef4dd248-4df5-4484-b750-ad318022120e.png)

the log says its vite plugin svelte so just filing it here to ask how to debug.

### Reproduction

try to run `yarn start` on https://github.com/sw-yx/swyxkit/blob/reportvitepluginsveltebug/src/routes/index.svelte and go to `localhost:3000`

### Logs

```shell
2:11:04 AM [vite] Internal server error:  Cannot read property 'index' of undefined
  Plugin: vite-plugin-svelte
  File: /Users/swyx/Work/Svelte/swyxkit/src/routes/index.svelte
```

### System Info

```shell
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Apple M1
    Memory: 44.02 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /var/folders/h_/1lq46tdj7jdbs0j1m5l6rlb00000gn/T/fnm_multishell_34699_1641060781509/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /var/folders/h_/1lq46tdj7jdbs0j1m5l6rlb00000gn/T/fnm_multishell_34699_1641060781509/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 94.0.2
    Safari: 14.1
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.37 => 1.0.0-next.37 
    @sveltejs/kit: ^1.0.0-next.208 => 1.0.0-next.208 
    svelte: ^3.44.3 => 3.44.3 
```
```


### Severity

annoyance

**Comment by bluwy** [comment]
I think you're missing an `export` for `export let REPO_URL`. But given the error in the first place, looks like Svelte doesn't handle that well, and outputs a cryptic message. I've made an issue there https://github.com/sveltejs/svelte/issues/7090. Closing in favour of it.
