### ISSUE TITLE
Tailwind CSS is placed after svelte's css

### ISSUE THREAD

**Issue by mustafa0x** [sveltejs/vite-plugin-svelte#248]
### Describe the bug

I'm working on a Vite / Svelte / Tailwind. I'm using `vite build --watch` (like `rollup -cw`) since I want the app to be served by another server (django).

Everything works fine, except that Tailwind's CSS reset is added to the very end of bundle.css. When I was using rollup I didn't have this problem.

My config might have an issue, but it's very simple. A simple fix would be to make sure tailwind's reset is saved to a different file, but I'm not sure that can be done.

On a tangent, is it possible to get HMR to work with `vite build --watch`? Or is livereload the best option in such a case.

### Reproduction

This is a very simple repo: https://github.com/mustafa0x/vite-svelte-test

Run `pnpm autobuild` and look at bundle.css. It will start with `ul.svelte-rqlssq{margin:1rem}*,::before,::after ...`. Notice how the style I added (`ul`) was placed before tailwind's reset.

This is the vite.config:

```js
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import livereload from 'rollup-plugin-livereload'
import svelte_preprocess from 'svelte-preprocess'
import tailwindcss from 'tailwindcss'

let production = !process.argv.includes('--watch')
const intro = `window.__BUILD_DATE__ = '${(new Date).toISOString()}';`

const tailwind = tailwindcss({
    content: ['./src/**/*.{html,js,svelte}'],
})

export default defineConfig({
    publicDir: false,
    build: {
        outDir: 'public/assets/',
        emptyOutDir: false,
        minify: false,
        sourcemap: !production,
        lib: {
            entry: 'src/main.js',
            formats: ['es'],
            fileName: (format) => `bundle.${format}.js`,
        },

        rollupOptions: {
            output: {
                intro,
                entryFileNames: 'bundle.js',
                assetFileNames: 'bundle.css',
            },
        },
    },
    plugins: [
        svelte({
            preprocess: [
                svelte_preprocess({postcss: {plugins: [tailwind]}}),
            ],
        }),
        !production && livereload({watch: 'public/assets/{bundle.js,bundle.css}'}),
    ],
})
```

### System Info

```shell
Binaries:
    Node: 15.5.0 - /usr/local/bin/node
    npm: 7.3.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.33 => 1.0.0-next.34 
    svelte: ^3.44.3 => 3.45.0 
    vite: ^2.7.10 => 2.7.10 
```

### Severity

annoyance

**Comment by dominikg** [comment]
Please try to set up tailwind with https://github.com/svelte-add/tailwindcss 

hmr is not possible with build.

**Comment by mustafa0x** [comment]
Thanks!

svelte-add's approach creates a couple unneeded files, which I would prefer to avoid.

I found a work around: I added `import 'tailwindcss/src/css/preflight.css'` to "main.js" and removed `@tailwind base;`.

There's no obvious way to tell vite to create multiple CSS files in this case, is there?

> hmr is not possible with build.

Do you have any recommendations for my situation? I.e. when the app needs to be served by another server instead of vite. An alternative is to run on different ports, but that causes CORS and other problems. Maybe vite can somehow proxy requests...

**Comment by dominikg** [comment]
importing tailwind via a css file in main.js is one of the things the aforementioned svelte-add does.
That setup is the recommended way, use others at your own risk.

proxying in vite devserver is possible. Please consult the docs. For more questions, you can join vite and svelte discord servers.

**Comment by mustafa0x** [comment]
Thank you; much appreciated.
