### ISSUE TITLE
Support for ESM configs

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/vite-plugin-svelte#29]
**Describe the feature**
Support loading ESM config files. Currently only CommonJS `svelte.config` files are supported because the code uses `require` to load it.

I think that [this line](https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/src/utils/loadSvelteConfig.ts#L21) needs to change to use `import(..)` . Note though that TS will transpile this to a `require` anyway, that's why you need to create a `const dynamicImport = new Function('path', 'return import(path)');` function and use that one as a workaround (see https://github.com/microsoft/TypeScript/issues/43329 for more info).

**A Usecase**
Support ESM `svelte.config.js` in SvelteKit

**Alternatives**
none

**Additional context**
Blocker for https://github.com/sveltejs/kit/pull/936

**Comment by dominikg** [comment]
Needs support for async config from vite, this has been merged but not released https://github.com/vitejs/vite/pull/2758

Also does this mean that going forward there will be no svelte.config.cjs and we should discourage its use or are both allowed?

And while we're at it, whats the list of locations vite-plugin-svelte should look for svelte.config.c?js ?  (see https://github.com/sveltejs/vite-plugin-svelte/issues/23 for context)

**Comment by dominikg** [comment]
Update, async config hook might be a better place: https://github.com/vitejs/vite/pull/2800

**Comment by dummdidumm** [comment]
Both `cjs` and `js` should be supported. It should check `.js` first, then `.cjs` to be in line with the order how language-tools and SvelteKit (will) resolve it.

Regarding "where to look": I think this was never specified. But we should, at some point, to save us some maintenance 😄

**Comment by dominikg** [comment]
Initial code here https://github.com/sveltejs/vite-plugin-svelte/compare/feat/async-load-config-esm  needs to wait until vite 2.16 is released and peer dependency updated.

should we try to get rid of everything non-esm and make vite-plugin-svelte itself a type: module too? 

Here's another require call: https://github.com/sveltejs/vite-plugin-svelte/blob/a2acab981c91dd47aa036798ef0bf79d9c805342/packages/vite-plugin-svelte/src/index.ts#L161 , anything else?

**Comment by dummdidumm** [comment]
You also need to replace the `require-relative` dependency I think.

**Comment by janosh** [comment]
Very interested in this PR. Anything I can do to help?

**Comment by dominikg** [comment]
unfortunately jest doesn't really support esm, so a fallback to cjs is needed.

@dummdidumm would it be ok to require the cjs extension or fallback to require if import throws?

**Comment by dummdidumm** [comment]
Fine with me, if `import()` throws for real users later on there's not much you can do anyway.

**Comment by dominikg** [comment]
released in 1.0.0-next.8

**Comment by dummdidumm** [comment]
I encountered a bug on windows. It tells me that the given path is not a valid scheme. Seeing that I remembered that I had the same issue in language-tools and what I did was wrapping the path with `pathToFileUrl` - sorry for not catching that earlier.
