### ISSUE TITLE
third-party package is falsely required to export package.json

### ISSUE THREAD

**Issue by mcmxcdev** [sveltejs/vite-plugin-svelte#299]
### Describe the bug

I am using the `p-limit` package which throws the following warning when building with SvelteKit:

```
[vite-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
- p-limit
- yocto-queue
```

According to the owner of the package, this is a mistake on the end of `vite-plugin-svelte`: https://github.com/sindresorhus/p-limit/issues/62

### Reproduction

- install `p-limit` package
- use it in code
- run `pnpm build` in a SvelteKit starter template
- expect warning to pop up

### System Info

```shell
System:
    OS: Linux 5.16 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
    Memory: 6.71 GB / 15.61 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 16.14.1 - ~/.volta/tools/image/node/16.14.1/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.5.0 - ~/.volta/tools/image/node/16.14.1/bin/npm
Browsers:
    Brave Browser: unknown
    Firefox: 98.0.1
npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: 1.0.0-next.299 => 1.0.0-next.299 
    svelte: ^3.46.4 => 3.46.4
```

### Severity

annoyance

**Comment by bluwy** [comment]
We've removed the warning since https://github.com/sveltejs/vite-plugin-svelte/pull/272. Are you on the latest version of vite-plugin-svelte?

**Comment by mcmxcdev** [comment]
I used `@sveltejs/kit/1.0.0-next.299` which required `@sveltejs/vite-plugin-svelte': 1.0.0-next.34`

Upgrading to `@sveltejs/kit/1.0.0-next.302` pulled in `@sveltejs/vite-plugin-svelte': 1.0.0-next.40` which indeed removed the warning ;)

Thanks!
