### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by benmccann** [sveltejs/vite-plugin-svelte#3]
Caching was turned off in SvelteKit https://github.com/sveltejs/kit/pull/576/files#diff-ed48923f0655f935bee505cdcbf40212129ff49a89c2c9d752bd63aa1e6282c4R98

Seems to be necessary due to caching issues here: https://github.com/sveltejs/kit/issues/572

**Comment by dominikg** [comment]
I'be been trying to investigate this but still lack understanding whats happening and why.
Added a playground with a default kit project to this repo and put some basic tests.
https://github.com/sveltejs/vite-plugin-svelte/blob/kit-playground/packages/playground/kit-node/__tests__/kit.spec.ts

no errors.

**Comment by dominikg** [comment]
successful test run on ci: https://github.com/sveltejs/vite-plugin-svelte/runs/2161661819
eg windows result: https://github.com/sveltejs/vite-plugin-svelte/runs/2161661819?check_suite_focus=true#step:10:30

**Comment by dominikg** [comment]
transform cache was removed and no further caching issues have been mentioned. c
