### ISSUE TITLE
"Sourcemap points to missing source files" for all svg imports

### ISSUE THREAD

**Issue by yowzadave** [sveltejs/vite-plugin-svelte#301]
### Describe the bug

When using rollup-plugin-svelte-svg (https://github.com/codefeathers/rollup-plugin-svelte-svg), any imported svgs throw the warning:

```
Sourcemap for "/.../my-icon.svg.rollup-plugin.svelte" points to missing source files
```

The images load properly; the only problem is the erroneous warning message.

### Reproduction

https://github.com/yowzadave/svg-import-demo

Running "vite" in this repository will reproduce the error.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 86.17 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.1 - ~/.nvm/versions/node/v17.3.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v17.3.1/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v17.3.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Firefox: 98.0.2
    Safari: 15.2
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.30 => 1.0.0-next.40 
    svelte: ^3.44.0 => 3.46.4 
    vite: ^2.8.0 => 2.8.6
```

### Severity

annoyance

**Comment by dominikg** [comment]
The console warning comes directly from vite and is caused by rollup-plugin-svelte-svg's custom id format.

I recommend you check out unplugin-icons, or unocss with preset-icons as alternative solution or report this directly on rollup-plugin-svelte-svg.

**Comment by bluwy** [comment]
Also a note: You can pass `extensions: ['.svelte', '.svg']` to the plugin options. Another rollup plugin isn't really needed, unless you want to run svgo, and that can be done with https://github.com/svitejs/svelte-preprocess-svg too.

**Comment by yowzadave** [comment]
Thanks @dominikg and @bluwy--I'll try your suggestions!
