### ISSUE TITLE
Monaco Editor: Unexpected chunking / missing CSS 

### ISSUE THREAD

**Issue by mattfysh** [sveltejs/vite-plugin-svelte#31]
## Description

A number of issues demonstrated in the linked repro repo. I'm not sure if this is a vite-plugin-svelte issue, or a vite issue

1. In prod mode, CSS is missing
2. In dev mode, CSS files in optimized (esbuild) deps are requested individually, causing page slowdown
3. The code that contains the worker import statement is being bundled inside the wrong chunk

## Reproduction

https://github.com/mattfysh/vite-and-monaco

## Additional Information

- The output of `npx envinfo --system --npmPackages vite,svelte,svelte-hmr,@sveltejs/vite-plugin-svelte --binaries --browsers`

```
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 2.27 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 89.0.4389.128
    Safari: 14.0.3
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.6 => 1.0.0-next.6 
    svelte: ^3.37.0 => 3.37.0 
    vite: ^2.1.5 => 2.1.5 
```

- debug logs produced with `vite dev --debug vite-plugin-svelte` or `DEBUG=vite-plugin-svelte <your start command here>`

See linked repro repo

**Comment by dominikg** [comment]
This reads like issues in vite itself. Did you try to reproduce it in a vanilla vite setup? 
`npm init @vitejs/app --template vanilla`

**Comment by mattfysh** [comment]
Yeah I was able to remove the svelte plugin as well as monaco and reproduce with some Vite + a few small JS files. Thanks!
