### ISSUE TITLE
Provide an option to exclude files from HMR

### ISSUE THREAD

**Issue by IanVS** [sveltejs/vite-plugin-svelte#321]
### Describe the problem

In the storybook vite builder, we have a problem with svelte stories not correctly reloading when changes are made to files.  I don't completely understand what's going on, but story files are watched by the manager webpack so that it can HMR the list of files, but that makes them incompatible for vite HMR, it seems.  We had the same problem with react stories, and the solution was to exclude stories from HMR, allowing the page to reload instead when changes are made.

However, it seems there's no such option for svelte to control when HMR happens.  It's only on or off, as far as I can tell.

### Describe the proposed solution

It would be great if you could support an `include/exclude` set of globs, much like rollup transform plugins or @vitejs/plugin-react: https://github.com/vitejs/vite/tree/main/packages/plugin-react#filter-which-files-use-fast-refresh

### Alternatives considered

I can turn off HMR entirely for svelte projects, but that doesn't seem like a great option.  HMR is working just fine when editing components, just not stories.

### Importance

would make ~my life~ the life of storybook users easier

**Comment by dominikg** [comment]
As far as i am aware storybook is not going to support authoring stories in svelte format going forward, and focuses on their own component story format (csf) instead. 

So i'm not really sure how csf stories would end up being processed by vite-plugin-svelte.

As a workaround you could create 2 instances of vite-plugin-svelte that operate on disjunct sets with include/exclude:

```js
const storyPattern = "**/*.story.svelte";
export default {
  plugins:[
    svelte({exclude: storyPattern}),
    {
      ...svelte({include: storyPattern, hot: false}), 
      name: "vite-plugin-svelte-stories" // avoid 2 plugin instances with same name
    }
  ]
}
```

**Comment by bluwy** [comment]
If the workaround works, I think it is the solution instead of adding another option for this case, as `include` and `exclude` options are meant for this usecase.
