### ISSUE TITLE
Could not resolve .js import from ts svelte component

### ISSUE THREAD

**Issue by shir0u** [sveltejs/vite-plugin-svelte#323]
### Describe the bug

When `type: module` is used in package.json, the specification says that any import should have an extension. Following convention, if we add .js import for a typescript file, it is not able to resolve.

### Reproduction

```svelte
<script lang="ts">
import foo from './some-typescript-file.js';
console.log(foo);
</script>
```

This works with a regular .ts file, but not a svelte file using ts context.

### Logs

```shell
Errors:

Could not resolve './some-typescript-file.js' from App.svelte
```
```


### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 48.13 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 98.0.2
    Safari: 15.4
  npmPackages:
    @sveltejs/vite-plugin-svelte: 1.0.0-next.42 => 1.0.0-next.42 
    svelte: 3.48.0 => 3.48.0 
    vite-system:  2.9.6
```

### Severity

blocking all usage of vite-plugin-svelte

**Comment by bluwy** [comment]
Was just looking at this yesterday: https://github.com/vitejs/vite/pull/7998. Got a fix for Vue but will port the fix here too once that's merged.
