### ISSUE TITLE
[vite:load-fallback] Could not load .../node_modules/svelte/internal/index.mjs

### ISSUE THREAD

**Issue by patbhakta** [sveltejs/vite-plugin-svelte#327]
### Describe the bug

Windows 10 can access the NAS drive, VS Code can, npm init can, however on npm build that seems vite has a problem.  The file index.mjs can be accessed from VS Code, CMD and Powershell. The same setup done locally doesn't create this issue.

`X:\SvelteKit\Docker>npm run build

> docker@0.0.1 build
> svelte-kit build

vite v2.9.8 building for production...
✓ 4 modules transformed.
[vite:load-fallback] Could not load /192.168.50.5/dev/SvelteKit/Docker/node_modules/svelte/internal/index.mjs (imported by src/routes/__layout.svelte): ENOENT: no such file or directory, open 'X:\192.168.50.5\dev\SvelteKit\Docker\node_modules\svelte\internal\index.mjs'
> Could not load /192.168.50.5/dev/SvelteKit/Docker/node_modules/svelte/internal/index.mjs (imported by src/routes/__layout.svelte): ENOENT: no such file or directory, open 'X:\192.168.50.5\dev\SvelteKit\Docker\node_modules\svelte\internal\index.mjs'`

### Reproduction

create a folder on network drive
run 'npm init svelte@next .'

select SvelteKit demo app
None for Type Checking
No for ESLinting
No for Playwrite

run 'npm install'
run 'npm run build' should trigger the vite error

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
    Memory: 109.24 GB / 127.91 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.73
    @sveltejs/kit: next => 1.0.0-next.326
    svelte: ^3.46.0 => 3.48.0
```

### Severity

annoyance

**Comment by dominikg** [comment]
This is an issue in vite
https://github.com/vitejs/vite/issues/5010

Maybe enabling `preserveSymlinks`  can help you https://github.com/vitejs/vite/issues/5010#issuecomment-1091146386

In general i would not recommend working with remote/network file systems during dev and especially on windows keep everything related to your project on the same drive letter, do not use junctions

**Comment by dominikg** [comment]
going to close this here as it isn't an issue with vite-plugin-svelte itself. 
Please follow the upstream issue https://github.com/vitejs/vite/issues/5010
