### ISSUE TITLE
The argument 'filename' must be a file URL object, file URL string, or absolute path string.

### ISSUE THREAD

**Issue by Nisthar** [sveltejs/vite-plugin-svelte#340]
### Describe the bug

I am using tailwindcss, videojs
This is my dependencies.

```
	"devDependencies": {
		"@bytemd/plugin-gemoji": "^1.13.1",
		"@bytemd/plugin-gfm": "^1.13.1",
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "^1.0.0-next.287",
		"@tailwindcss/forms": "^0.5.1",
		"autoprefixer": "^10.4.2",
		"bytemd": "^1.13.1",
		"github-markdown-css": "^5.1.0",
		"postcss": "^8.4.7",
		"prettier": "^2.5.1",
		"prettier-plugin-svelte": "^2.5.0",
		"sass": "^1.49.9",
		"slugify": "^1.6.5",
		"svelte": "^3.46.0",
		"svelte-calendar": "^3.1.6",
		"svelte-image": "^0.2.9",
		"svelte-intersection-observer": "^0.10.0",
		"svelte-preprocess": "^4.10.4",
		"tailwindcss": "^3.0.23",
		"vite-imagetools": "^4.0.3"
	},
	"type": "module",
	"dependencies": {
		"@fontsource/fira-mono": "^4.5.0",
		"@lottiefiles/lottie-player": "^1.5.7",
		"@lukeed/uuid": "^2.0.0",
		"@vime/core": "^5.3.1",
		"cookie": "^0.4.2",
		"daisyui": "^2.2.2",
		"dayjs": "^1.11.0",
		"dotenv": "^16.0.0",
		"lodash": "^4.17.21",
		"socket.io-client": "^4.4.1",
		"svelte-infinite-scroll": "^2.0.1",
		"svelty-picker": "^1.2.4",
		"video.js": "^7.18.1"
	}

```

	
I am getting the following error
	
![image](https://user-images.githubusercontent.com/11994157/168558594-4906a39a-dc04-4d3e-a8b0-5b4041958690.png)

The error seems to be vague. idk if any dependencies is causing the error.

### Reproduction

[vite-plugin-svelte] The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '\x00__vite-browser-external?commonjs-proxy'
> The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '\x00__vite-browser-external?commonjs-proxy'
    at new NodeError (node:internal/errors:371:5)
    at createRequire (node:internal/modules/cjs/loader:1216:13)
    at resolveViaPackageJsonSvelte (file:///D:/node_projects/myapp-client/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1427:26)   
    at Object.resolveId (file:///D:/node_projects/myapp-client/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1585:24)
    at D:\node_projects\myapp-client\node_modules\rollup\dist\shared\rollup.js:22795:37
[!] Error: unfinished hook action(s) on exit:
(vite:css) transform "D:/node_projects/myapp-client/src/app.css"     
(vite:css) transform "D:/node_projects/myapp-client/src/lib/components/User/UserAvatar.svelte?svelte&type=style&lang.css"
(vite:css) transform "D:/node_projects/myapp-client/src/lib/components/User/UserFeed.svelte?svelte&type=style&lang.css"
(vite:css) transform "D:/node_projects/myapp-client/src/lib/components/Search/FilterSidebar.svelte?svelte&type=style&lang.css"
(vite:css) transform "D:/node_projects/myapp-client/src/lib/components/Loading.svelte?svelte&type=style&lang.css"
(vite:css) transform "D:/node_projects/myapp-client/src/lib/components/User/WritePost.svelte?svelte&type=style&lang.css"
(vite:css) transform "D:/node_projects/myapp-client/src/lib/components/User/UserComment.svelte?svelte&type=style&lang.css"
(vite:css) transform "D:/node_projects/myapp-client/node_modules/svelte-calendar/components/Datepicker.svelte?svelte&type=style&lang.css"    
(vite:css) transform "D:/node_projects/myapp-client/node_modules/svelte-calendar/components/InlineCalendar.svelte?svelte&type=style&lang.css"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/@videojs/vhs-utils/es/resolve-url.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/m3u8-parser/dist/m3u8-parser.es.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/@videojs/vhs-utils/es/codecs.js"   
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/@videojs/vhs-utils/es/media-types.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/mpd-parser/dist/mpd-parser.es.js"  
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/mux.js/lib/tools/parse-sidx.js"    
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/@videojs/vhs-utils/es/id3-helpers.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/@videojs/vhs-utils/es/containers.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/@videojs/vhs-utils/es/byte-helpers.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/mux.js/lib/utils/clock.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/postcss/lib/postcss.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/svelte-calendar/components/generic/KeyControls.svelte"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/svelte-calendar/components/generic/Grid.svelte"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/svelte-calendar/components/generic/Arrow.svelte"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/engine.io-parser/build/esm/index.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/parseqs/index.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/engine.io-client/build/esm/transports/polling-xhr.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/engine.io-client/build/esm/transports/websocket.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/engine.io-client/build/esm/globalThis.browser.js"
(vite:load-fallback) load "D:/node_projects/myapp-client/node_modules/@babel/runtime/helpers/esm/setPrototypeOf.js"

### System Info

```shell
System:
    OS: Windows 10 10.0.22000       
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 7.39 GB / 15.85 GB      
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\Volta\tools\image\node\16.14.0\node.EXE
    Yarn: 1.22.17 - ~\AppData\Local\Volta\tools\image\yarn\1.22.17\bin\yarn.CMD
    npm: 8.3.1 - ~\AppData\Local\Volta\tools\image\node\16.14.0\npm.CMD 
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.47)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.29
    @sveltejs/kit: ^1.0.0-next.287 => 1.0.0-next.287
    svelte: ^3.46.0 => 3.46.4
```

### Severity

blocking all usage of vite-plugin-svelte

**Comment by dominikg** [comment]
Your dependencies are out of date (sveltekit is at next.330 now). Please check if the problem still occurs with the most recent versions of sveltekit, vite and vite-plugin-svelte.

If it does, provide a minimal reproduction in a stackblitz or github repository. Only include the dependency that causes this problem.

**Comment by Nisthar** [comment]
unfortunately its still happening on the latest version. I tried debugging the error on vscode

![image](https://user-images.githubusercontent.com/11994157/168570314-74182a6a-5f66-433e-bd62-8830c360768e.png)

Is there a way to know what's causing this error?

**Comment by Nisthar** [comment]
It might be a module that's causing this issue.

**Comment by Nisthar** [comment]
@dominikg why isn't this already added into the library?

**Comment by dominikg** [comment]
No repro provided. We will consider reopening when you provided one
