### ISSUE TITLE
WSL2 support for inspector

### ISSUE THREAD

**Issue by khromov** [sveltejs/vite-plugin-svelte#355]
### Describe the problem

When using this with Windows 10/11 + WSL2, there are two issues:

* When clicking on a component, it doesn't open VS Code but rather opens a `vim` window in the SSH console. It also doesn't respond correctly to keypresses so you can't exit vim. 🙀 
* Neither the default key combo (I assume it'll pick the Linux one since WSL is typically running Ubuntu or Debian) nor manually configuring `ctrl-shift` seems to work. Only setting `showToggleButton: 'always'` works.

### Describe the proposed solution

Perhaps there is some way for the plugin to understand that it's running in WSL2 + VSCode and send a message to the VS Code process?

### Reproduction

1. Install Windows 10 / 11 + WSL2 (Either manually or via Microsoft Store on Windows 11).
2. Install the [Ubuntu](https://apps.microsoft.com/store/detail/ubuntu/9PDXGNCFSCZV?hl=en-us&gl=US) app from Microsoft Store. 
3. Install VSCode [guide](https://code.visualstudio.com/docs/remote/wsl).
4. Launch any normal Svelte project with the inspector configured.

### Alternatives considered

-

### Importance

nice to have

**Comment by dominikg** [comment]
vite uses `launch-editor` to open your editor, WSL support is requested here: https://github.com/yyx990803/launch-editor/issues/16

You may be able to set the vscode executable in the `EDITOR` environment variable as launch-editor supports that too.

Regarding key-combo, i'm a bit confused, ctrl-shift worked when i used it in a virtual machine (i don't have a native windows installation). Please try other combos to see if any of them work. eg `ctrl-e`. 

Note it is not recommended to use printable letters together with `holdMode: true`

**Comment by dominikg** [comment]
please let us know if EDITOR helps with your issue and if there is a key-combo that works for you.

**Comment by dominikg** [comment]
Going to close this here, please follow the upstream issue for picking a more suitable editor in WSL https://github.com/yyx990803/launch-editor/issues/16

Feedback regarding the keycombo is also still welcome though in my testing ctrl-shift did work fine in my windows vm and given you can configure any other combo of your chosing to work around local collisions there's little more v-p-s could do to improve the situation
