### ISSUE TITLE
configure vitest for component libraries

### ISSUE THREAD

**Issue by dominikg** [sveltejs/vite-plugin-svelte#358]
### Describe the problem

vitest uses node to load esm imports, which fails for svelte libraries that export `.svelte` files from an esm `index.js`.

see #350 
and a discussion on vitest discord https://discord.com/channels/917386801235247114/917386801235247117/981407875073208380

### Describe the proposed solution

vitest has an option `deps.inline` that can be used to load them with vite instead of node

we already collect svelte dependencies for vite config optimizeDeps handling, use the information gathered there to add 
`test.deps.inline:[...svelteComponentLibs]`  to vite config if vite config contains a `test` key.

also see https://discord.com/channels/917386801235247114/917386801235247117/981569088516157440

### Alternatives considered

1) extend vitest to either check file extensions and fall back to vite automatically for unknown extensions or add try/catch and retry failed imports with vite. 
Both would require changes to vitest that may also affect others and they have expressed that they see this as the frameworks responsibility to configure vitest accordingly.

2) just document it and let users add deps.inline for dependencies they need in their tests

### Importance

would make my life easier

**Comment by bluwy** [comment]
IIUC from the [docs](https://vitest.dev/config/#deps), it seems like `deps.inline` and `deps.external` works the same as `ssr.noExternal` and `ssr.external`? I think Vitest should use the SSR options instead of declaring another configuration point (if it makes sense). So I don't think we should give special treatment for Vitest to we are more platform agnostic. cc @sheremet-va from the referenced discord discussion.

**Comment by sheremet-va** [comment]
> IIUC from the [docs](https://vitest.dev/config/#deps), it seems like `deps.inline` and `deps.external` works the same as `ssr.noExternal` and `ssr.external`? I think Vitest should use the SSR options instead of declaring another configuration point (if it makes sense). So I don't think we should give special treatment for Vitest to we are more platform agnostic. cc @sheremet-va from the referenced discord discussion.

Good point. I will discuss it with the team.

**Comment by sheremet-va** [comment]
We think asking people to put configuration options into `ssr` field is not very intuitive, but we think that we can merge`ssr` options with `deps.inline`/`deps.external`, what do you think? @bluwy

**Comment by bluwy** [comment]
I think that's a fine compromise. Thanks for checking that! I still think that leaning 100% on SSR options would be great though, as I'd imagine vite-node is part of the SSR domain, but maybe there are usecases that y'all see to have it better separated.

Nonetheless I'll go ahead and close this then as the change would be done in Vitest side.

**Comment by sheremet-va** [comment]
@bluwy sorry to bother you, but can you give an example of `ssr`'s usage? I cannot seem to find it in resolved config and/or on `server.config`.

> I'd imagine vite-node is part of the SSR domain

It transforms files with `ssr` flag only if specified (by default only `ts` files). Svelte files, for example, are transformed without `ssr` flag. But I do think it should be done in ViteNode itself, this could help Histoire in the future.

**Comment by bluwy** [comment]
> @bluwy sorry to bother you, but can you give an example of `ssr`'s usage? I cannot seem to find it in resolved config and/or on `server.config`.

It should be [this one](https://vitejs.dev/config/#ssr-options). Usually it would be set like:
```js
export default defineConfig({
  ssr: {
    noExternal: ['a-svelte-lib', 'special-edge-case-lib']
  }
})
```



> It transforms files with `ssr` flag only if specified (by default only `ts` files). Svelte files, for example, are transformed without `ssr` flag. But I do think it should be done in ViteNode itself, this could help Histoire in the future.

Interesting. I don't think there's a correct way for svelte+ssr part as Vitest could run happy-dom when loading/testing Svelte components, but great to know.

**Comment by sheremet-va** [comment]
So, 
- `noExternal` means in will be transformed with `Vite` pipeline, correct?
- `external` means it will just be `required`/`imported`?

I made a first version with this assumption, but all Vue tests fail, because they `externalize` Vue and don't have correct `exports` fields :S

**Comment by bluwy** [comment]
> So,
> 
> * `noExternal` means in will be transformed with `Vite` pipeline, correct?
> * `external` means it will just be `required`/`imported`?

Yup 👍 

Re `vue` yeah it seems like the case too unfortunately. Might need hardcoded handling since it's a popular library.

**Comment by dominikg** [comment]
we may need to always generate the ssr config in vite-plugin-svelte then too. Iirc it is currently only generated for `build --ssr`
