### ISSUE TITLE
Can't set custom css hash

### ISSUE THREAD

**Issue by ahmed-abdelmotey** [sveltejs/vite-plugin-svelte#369]
### Describe the problem

the cssHash option is ignored deliberatly, please let us know if this is for a reason. 

### Describe the proposed solution

user can provide custom cssHash function,

### Alternatives considered

N/A

### Importance

would make my life easier

**Comment by dominikg** [comment]
https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#why-cant-csshash-be-set-in-development-mode
