### ISSUE TITLE
Option to specify an editor for svelte-inspector

### ISSUE THREAD

**Issue by inspiredlabs** [sveltejs/vite-plugin-svelte#380]
### Describe the problem

There's a lot of text editors out there. I switch editors for different tasks using `cmd + tab` on macOS or `alt + tab` on Windows.

### Describe the proposed solution

Is there a way to help people configure default file types?

This Visual Studio Code system default was particularly useful:

`defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add '{LSHandlerContentType=public.plain-text;LSHandlerRoleAll=com.microsoft.VSCode;}'`

- from Chris Ferdinandi's blog: https://gomakethings.com/changing-the-default-text-editor-on-macos/

### Alternatives considered

Configure/advise which editor the inspector opens.

### Importance

would make my life easier

**Comment by dominikg** [comment]
We use vite to open files which in turn uses launch-editor. You should be able to specify your editor with `EDITOR` or `VISUAL` env. 

This https://github.com/yyx990803/launch-editor/pull/39 is going to help in cases where multiple editors are open and it picks the wrong one

**Comment by dominikg** [comment]
This needs to be handled upstream in launch-editor
