### ISSUE TITLE
drop support for sapper studio or update comment

### ISSUE THREAD

**Issue by benmccann** [sveltejs/vite-plugin-svelte#397]
### Describe the bug

there's a line referring to sapper studio. not quite sure what that is, but pretty sure we don't need to support it :smile: is there code that can be removed or should we update the comment to say VS Code or something?

### Reproduction

https://github.com/sveltejs/vite-plugin-svelte/blob/b523d7570c55145d9a400f3d067f1ad341629302/packages/vite-plugin-svelte/src/handle-hot-update.ts#L108

### System Info

```shell
latest
```

### Severity

annoyance

**Comment by dominikg** [comment]
yes, that comment is from the early days. the main point is that it doesn't affect user code.
