### ISSUE TITLE
Vite plugin logs? Open source of console.log in VSCode (like the inspector in vite-plugin-svelte)

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/vite-plugin-svelte#400]
### Describe the problem

When I see the log, I have to go into VSCode myself, find the file, the line of code.
And Firefox DevTools Console has a link to that line in that file.

Microsoft Edge has this DevTools function:
![obraz](https://user-images.githubusercontent.com/16800535/180593787-ce334135-f897-4809-a4e3-b850d25fefd4.png)
But Firefox doesn't.

I thought that if there is an inspector in vite-plugin-svelte, maybe it is possible to do something similar, for Console? For logs?

### Describe the proposed solution

The button and shortcut that calls Popup window, above the page, with a list of logs, with url to files in VSCode.

Same as inspector in vite-plugin-svelte for DOM elements.

Just as inspector in vite-plugin-svelte replaces DevTools Inspect, this is to replace DevTools Console.

In the future: WebExtension with a panel that contains these logs.

### Alternatives considered

Wait for Firefox to introduce a solution with Microsoft Edge - https://bugzilla.mozilla.org/show_bug.cgi?id=1771862
(so far no response)

### Importance

would make my life easier

**Comment by dominikg** [comment]
while this sounds like a feature that could be helpful, it is very generic and not directly related/restricted to svelte.  So i'm sorry but this is out of scope for vite-plugin-svelte. 

Could be implemented in a separate vite-plugin-linked-console

**Comment by lukaszpolowczyk** [comment]
If anyone needs it, I found an easy way to do it right now, without a plugin and without browser functionality.

Just add the code to `src/app.html`, and it works already.

It looks like this:
![console](https://user-images.githubusercontent.com/16800535/181167453-3e4d6e1d-f0f5-433d-847a-78fe1c484e5f.png)
Just click the url in the console containing `/__open-in-editor?file=` in it, and VSCode will open what you need.

It works in Firefox, Chrome, Edge, Vivaldi.

I can already say that it is very convenient. :D
**I dream that Mozilla will add this to their DevTools in a refined version.
Or Vite plugin to be created, with a separate console that does not have the flaws that are in this script of mine.**

Known problems:
1. The code is asynchronous due to the use of fetch and wasm, making console.log/warn/error/info asnchronous. It seems to me that this is not a problem most of the time, it's just that the logs appear in a desynchronized way, you don't need to call them with await.
2. When there is no code map for a file, it returns an XHR error in the console (map not loaded. unfortunately, I don't think it's possible to hide this XHR error), then the line and column number may be wrong (but it still links to the right file, just the wrong line). **Needed code maps in some places in Svelte, because it seems to be missing.**
3. When the script is enabled, the original links to the browser DevTools Debugger don't work - they all link only to the function associated with my script, because it substitutes every console.log/error/info/warn. **I wonder if it can be done better?**
4. Clicking the link to the editor opens a new tab in the web browser, which you have to manually close later (but it's still less work than looking for a line in the file manually). **I'm thinking of a little extension for Firefox that detects tabs with `/__open-in-editor?file=`, and automatically closes them....**
5. The links are quite long. but nothing can be done about it.

I add this code ABOVE `%sveltekit.head%` in `src/app.html`, refresh the page in the browser, and done:
```html
<script src="https://unpkg.com/source-map@0.7.3/dist/source-map.js"></script>
<script>
	sourceMap.SourceMapConsumer.initialize({
			"lib/mappings.wasm": "https://unpkg.com/source-map@0.7.3/lib/mappings.wasm"
	});
</script>
<script type="module" async>
	export async function getPos (url, line, column) {
		const res = await fetch(`${url}.map`);
		const mapJson = await res.json();
		const place = await sourceMap.SourceMapConsumer.with(mapJson, null, consumer => {
			
			const place = consumer.originalPositionFor({
				line: Number(line),
				column: Number(column)
			});
			return place;
		});
		return place;
	}
	
	function uniConsole (name) {
		const n = `_${name}`;
		window[n] = console[name];
		const prefix = `${location.origin}/__open-in-editor?file=`;
		
		console[name] = function (...a) {
			try { throw Error(); } catch (err) {
				const stackLine = err.stack.includes("at ") ? (
					err.stack.split("\n")[2].includes("(") && err.stack.split("\n")[2].includes(")") ? (
						err.stack.split("\n")[2].split(")")[0].split("(")[1]
					) : err.stack.split("\n")[2].split("at ")[1]
				) : err.stack.split("\n")[1];
				
				if (stackLine) {
					const preUri = stackLine.split("@").at(-1).replace(`${location.origin}/`,"").replace(/^fs/, "");
					const path = preUri.split("?")[0].split(":")[0];
					
					const line = preUri.split("?").at(-1).split(":").at(-2);
					const column = preUri.split("?").at(-1).split(":").at(-1);
					
					if (path.length>0 && line && column) {
						getPos(`${location.origin}/${path}`, line, column).then(ob=>{
							if (ob.line && ob.column) {
								const { line, column } = ob;
								const target = `${path}:${ob.line}:${ob.column}`;
								window[n](...a, `${prefix}${target}`);
							} else {
								const target = `${path}:${line}:${column}`;
								window[n](...a, `${prefix}${target}`);
							}
						}).catch (error=>{
							const target = `${path}:${line}:${column}`;
							window[n](...a, `${prefix}${target}`);
						});
					} else
					if (path.length>0 && !line && !column) {
						const target = `${path}`;
						window[n](...a, `${prefix}${target}`);
					} else {
						const target = `${stackLine}`;
						window[n](...a, `${prefix}${target}`);
					}
				} else {
					window[n](...a, err.stack);
				}
			}
		}
	}
	uniConsole("log");
	uniConsole("warn");
	uniConsole("error");
	uniConsole("info");
</script>
```

Latest source-map version - https://github.com/mozilla/source-map/#use-on-the-web
