### ISSUE TITLE
Vue/react components cannot be used

### ISSUE THREAD

**Issue by mmm8955405** [sveltejs/vite-plugin-svelte#406]
### Describe the bug

Support either ESM or UMD, which can be imported and run

### Reproduction

Vue/react components cannot be used.   Support either ESM or UMD, which can be imported and run

### System Info

```shell
npm8
```

### Severity

annoyance

**Comment by dominikg** [comment]
please do not abuse our issue trackers, you already posted https://github.com/sveltejs/svelte/issues/7757 and it got closed.

I am doing the same here. 

Post a question to stackoverflow, ask on https://www.reddit.com/r/sveltejs/ or https://svelte.dev/chat .

**Comment by mmm8955405** [comment]
> please do not abuse our issue trackers, you already posted [sveltejs/svelte#7757](https://github.com/sveltejs/svelte/issues/7757) and it got closed.
> 
> I am doing the same here.
> 
> Post a question to stackoverflow, ask on https://www.reddit.com/r/sveltejs/ or https://svelte.dev/chat .

I didn't abuse issu!

This is a different project, don't you know?

However, the way you avoid problems is faster than a mouse
