### ISSUE TITLE
How to use customStyles doesn't seem defined in the docs?

### ISSUE THREAD

**Issue by jhubbardsf** [sveltejs/vite-plugin-svelte#424]
### Describe the bug

For experimental inspector there's a boolean called customStyles for injecting custom styles but I can't seem to find how to use it.

### Reproduction

NA

### Logs

```shell
NA
```

### System Info

```shell
NA
```

### Severity

annoyance

**Comment by jhubbardsf** [comment]
Ook, that actually part about having to inject global styles on my own is what I didn't understand. Thanks. I might suggest making that a little more explicit but maybe I'm just slow.

**Comment by dominikg** [comment]
Sorry, maybe i wasn't being clear enough in my response. 
svelte-inspector comes with one set of customStyles that can be turned on or off via the `customStyles` config option. That's it.

Overriding styles is not a supported feature, but it works if your app has conflicting styles.
However this won't be documented or be a part of our semver contract. classnames and styles can change with every release and are considered internal.

**Comment by jhubbardsf** [comment]
My main issue is that in some svelte sites I've worked on, I can't actually see the button or overlay because of z-index issues. That's what I'm trying to fix so I can go back to the correct solution (yours).
