### ISSUE TITLE
Using imported component multiple times (outside html)

### ISSUE THREAD

**Issue by TheMaikXX** [sveltejs/vite-plugin-svelte#433]
#### Inroduction
I have SPA with routing done with `svelte-spa-router` library which requires pages be specified as follows:
```
import ItemsPage from "../pages/ItemsPage.svelte"

const pages = {
	"/items": ItemsPage,
	"/items/:itemId": ItemsPage
}
```
In my case, I have both `/items` and `/items/123` pointing to same component because the page renders both table with items and optionally item detail card as well.

#### Observed error
When loading the page a runtime error occures:
`Uncaught ReferenceError: Cannot access 'ItemsPage' before initialization`
This error only appears if the `ItemsPage` component is referenced multiple times in single file (`/pages/index.js`).

I did not have this issue when using svelte with rollup

### Reproduction

Probably same as _Introduction_

### System Info

```shell
System:
    OS: Linux 5.19 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 50.34 GB / 62.72 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^1.0.1 => 1.0.4 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.7 => 3.0.9
```

### Severity

annoyance

**Comment by dominikg** [comment]
> Please provide a link to a repo and step by step instructions to reproduce the problem you ran into. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided within a reasonable time-frame, the issue will be closed.

**Comment by TheMaikXX** [comment]
While reproducing the issue I found an error in my code but that was not related to the issue.
Unfortunatelly I was unable to reproduce the same issue in a dedicated project..

Sorry for bothering.
Have a nice day
