### ISSUE TITLE
inspector - expand, narrow selection via +/- shortcut on keyboard

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/vite-plugin-svelte#435]
### Describe the problem

The inspector is great. The only shortcoming is that sometimes when I select an element, it opens the target component (e.g. Button.svelte) and not the container of that component (e.g. Nav.svelte).
Sometimes it's impossible to select precisely, because there's not even a margin to click in to select (in this case) Nav.svelte.

This feature is literally perfect, and I use it all the time.
This is the only thing missing.

### Describe the proposed solution

I press my toggleKeyCombo, and while holding it, I strangle the + key on the numeric keypad.
Then the selection should expand from button to parentElement, which is nav.
In the other direction, the - key on the numeric keypad.

### Alternatives considered

It doesn't.

### Importance

would make my life easier

**Comment by dominikg** [comment]
This is a nice idea. It would have to reset when moving the mouse over a different element though.
