### ISSUE TITLE
Enhancement: Extend HMR watching to .svelte components imported via SvelteKit's $lib shortcut

### ISSUE THREAD

**Issue by Slakinov** [sveltejs/vite-plugin-svelte#456]
I couldn't find mention of this anywhere else, not sure whether this is a SvelteKit issue or a svelte-hmr issue. Apologies if this is the wrong place to bring it up.

The problem: HMR recompiling is not triggered when editing components imported using SvelteKit's [$lib alias](https://kit.svelte.dev/docs/modules#$lib). The only way to see updates to components imported this way is to kill the dev process and restart.

Which package would be responsible for enabling this?

**Comment by dominikg** [comment]
Hi, i transferred this issue to vite-plugin-svelte as svelte-hmr isn't responsible for watching files.
Please provide a repository with a minimal reproduction / instructions how to reproduce.

**Comment by dominikg** [comment]
@Slakinov  a reproduction repo / instructions are required for us to be able to work on this. Closing here. Please refile and add all information required by our issue template if you are able to provide it.
