### ISSUE TITLE
Binding to app div not happening in SSR/SSG context

### ISSUE THREAD

**Issue by ryanweal** [sveltejs/vite-plugin-svelte#471]
### Describe the bug

I'm using the vite-plugin-svelte module directly within Vite and having trouble with the SSR process using the vite-plugin-ssr module.

I forked and updated the vite-plugin-ssr Svelte example code:

https://github.com/ryanweal/vite-plugin-ssr-svelte

And it seems to "work" if I bind to the target div on the client, however, in my server process, if I include any prerender HTML in the build, it will not bind to the div at all.

Here is the client & server side code:

https://github.com/ryanweal/vite-plugin-ssr-svelte/tree/main/pages/_default

From doing a prior demo using only vite+vite-plugin-svelte I was able to do this all within the index.html file, referencing a main.js, but in this server context of course window will not exist when I run main.js. Plus, with the vite-plugin-svelte module, it seems to support svelte files natively so perhaps I am trying to do too much?

I would appreciate if someone where could look at the two files in the _default folder above and let me know if there is anything really off about it that I am overlooking.

PS. I see the same issue in my custom from-scratch builds and followed all of the update/migration guides I am aware of. Feeling like I am missing something obvious.

### Reproduction

- Clone this repo: https://github.com/ryanweal/vite-plugin-ssr-svelte
- Do npm install
- Do npm run dev or npm run build and then serve the dist/client directory.

Note that things work like this, at least the counter should work.

If you disable JavaScript you will get a blank page. It did not really prerender.

edit pages/_default/_default.page.server.js and put ${dangerouslySkipEscape(appHtml)} in the div with the id=app (where the comment is) and you will now see prerendered html when you run `npm run build`... however, the app no longer loads int he client. you only get the static version.

### System Info

```shell
Linux, Node 16
```

### Severity

annoyance

**Comment by dominikg** [comment]
i'm sorry but this isn't an actionable bug report against vite-plugin-svelte.

SSR with vite-pluign-svelte works in general, as proven by sveltekit and the ssr tests in this very repo.

You can generate a simple ssr project bases on these tests with create-vite-extra: `pnpm create vite-extra my-svelte-ssr-app --template ssr-svelte`

For vite-plugin-ssr specific apis this repo isn't the right place to ask. I'd suggest you post a message on vite discord instead.

**Comment by ryanweal** [comment]
I had already posted on Discord which is why I wanted to ask here. I am sorry for asking. I know that the module is "proven" elsewhere but I have not been able to find much use outside of SvelteKit. I was hoping that someone who knows more than me might take a look after I've invested so many hours (and days at this point).

Regardless, after writing this issue up I was able to solve the problem.

Sorry about the noise. I suggest you may want to have a category for "questions" or "support" to make these questions easier to ignore.

Have a good day.
