### ISSUE TITLE
Inspector clicks do not open file with code in OSS Dev (VS Code built from source)

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [sveltejs/vite-plugin-svelte#474]
### Describe the bug

Hi! 
Sorry for the strange issue, I'm also new to Svelte.
I'm running a source build of VS Code and it seems like inspector clicks do not open the file in the editor. 

I'm guessing it has something to do with the fact that I run the editor from a script \vscode\scripts\code.bat. Even when I open normal files from explorer the batch script starts again, then opens the file in the open editor when it realizes that I actually have the editor open already. This may have something to do with that but it may also be something else, I have no idea. 

If you don't already have a source build reproducing this issue would require you to build OSS Dev, if that is annoying just closing the issue is fine. If not there is a guide here: https://github.com/microsoft/vscode/wiki/How-to-Contribute

The repro project is a project built with npm create vite@latest my-app -- --template svelte and the inspector enabled in vite.config.js.

### Reproduction URL

https://github.com/henrikvilhelmberglund/svelte-oss-dev-inspector-issue

### Reproduction

1. Build OSS Dev (https://github.com/microsoft/vscode/wiki/How-to-Contribute)
2. Run it with \vscode\scripts\code.bat
3. Fork my repo project or just do `npm create vite@latest my-app -- --template svelte` and enable the inspector in vite.config.js
4. Open the folder with OSS Dev
5. In the terminal run npm run dev
6. Open the site in a browser
7. Do ctrl+shift to enable the inspector and click somewhere
8. Result: nothing happens

Expected: the focus switches to the OSS Dev editor with the file opened and at the row of the thing you clicked on with the inspector.
I also tested it in VS Code (downloaded version) and it worked fine there so this seems like it's just an issue with source builds.

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
    Memory: 4.79 GB / 15.95 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Spartan (44.17763.831.0)
    Internet Explorer: 11.0.17763.771
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^1.0.2 => 1.0.9
    svelte: ^3.49.0 => 3.52.0
    vite: ^3.1.0 => 3.1.8
```

**Comment by dominikg** [comment]
the package that is responsible for launching the editor is `launch-editor` consumed via vite. it uses common binary names in your process list to find the editor you use. If the self-compiled version doesn't use the exact binary name of vscode, it might not get detected.

You can use an environment variable `LAUNCH_EDITOR` to point at a custom script that then calls your binary. It is documented here: https://github.com/yyx990803/launch-editor#to-run-a-custom-launch-script

There's little vite-plugin-svelte can do here. If the custom env does not work i suggest you file an issue in the launch-editor repo.
