### ISSUE TITLE
How do I silence naggy errors I don't care about?

### ISSUE THREAD

**Issue by staab** [sveltejs/vite-plugin-svelte#486]
### Describe the problem

I get the following warning when starting my dev server: `A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.` I don't care about this rule.

### Describe the proposed solution

I would like to disable the above warning.

### Alternatives considered

I found something similar in eslint, but the warning doesn't appear to be coming from there. I tried using [`onwarn`](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#onwarn), but I can't tell if it's supposed to go in vite.config.js or svelte.config.js. I tried both, neither worked.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
This should already be working. https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#config-file `onwarn` goes in the top level of your `svelte.config.js`. If it's not working, please share a minimal reproduction.

**Comment by dominikg** [comment]
please file a bug report providing all required information if this is not working as described in the docs mentioned.
