### ISSUE TITLE
Throws warnings with Svelte 3.53.0

### ISSUE THREAD

**Issue by patoi** [sveltejs/vite-plugin-svelte#489]
### Describe the bug

Throws warnings with Svelte 3.53.0: **"options.css as a boolean is deprecated. Use 'external' instead of false."**

```
9:46:34 AM [vite-plugin-svelte] /<repo>/node_modules/.pnpm/carbon-components-svelte@0.70.12/node_modules/carbon-components-svelte/src/icons/Information.svelte options.css as a boolean is deprecated. Use 'external' instead of false.
```
https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3530 changelog:

> Extend css compiler option with 'external' | 'injected' | 'none' settings and deprecate old true | false values (https://github.com/sveltejs/svelte/pull/7914)

### Reproduction URL

-

### Logs

```shell
9:46:34 AM [vite-plugin-svelte] /<repo>/node_modules/.pnpm/carbon-components-svelte@0.70.12/node_modules/carbon-components-svelte/src/icons/Information.svelte options.css as a boolean is deprecated. Use 'external' instead of false.
```

### System Info

```shell
not relevant
```

**Comment by dominikg** [comment]
the warning is removed in  svelte 3.53.1, update to get rid of it.

this will remain open until #490 is merged bc technically v-p-s is still providing outdated config defaults.
