### ISSUE TITLE
warn if removing `svelte` resolve override would break a package

### ISSUE THREAD

**Issue by benmccann** [sveltejs/vite-plugin-svelte#501]
### Describe the problem

Right now the `svelte` field is resolved first. We should eventually remove this and defer to Vite which will resolve `exports` first

### Describe the proposed solution

Add dependency on `@alloc/resolve.exports` to resolve the exports. If exports exist and resolve to different place than `svelte` field then warn.

### Alternatives considered

Discussed on Discord the the maintainers group and I think this is what we arrived at. I won't bother repeating the discussion

### Importance

nice to have

**Comment by dominikg** [comment]
love the idea of testing if resolve returns a different result with or without the svelte field.

We would have to issue a warning too for the case if removing the svelte field would fail resolving entirely if there is no exports map or other entries. Right now this package.json is legal for svelte libraries


```json
{
  "name": "some-lib",
  "svelte": "index.js"
}
```

not sure we need the external lib for this, can't we just leverage vite's `this.resolve` or something ?

**Comment by benmccann** [comment]
@dummdidumm suggested continuing to support the `svelte` field, which seems reasonable to me. I think the thing we really need to change is that it has precedence over `exports`. In that case we wouldn't need any warnings for the example file above.

I didn't realize Vite exported `this.resolve`. Using that instead of an external library sounds good to me.
