### ISSUE TITLE
Add option to auto-close inspector after a component has been opened 

### ISSUE THREAD

**Issue by LorisSigrist** [sveltejs/vite-plugin-svelte#518]
### Describe the problem

If you've used the inspector for any amount of time, you will have run into this:

1. Open Component using inspector -> Window switches to IDE
2. Do some editing 
3. Switch back to browser to see the result and immediately start clicking stuff, forgetting the inspector is still on -> Get sent back to the IDE by accident

This can be very frustrating, as it is quite easy to forget the inspector is still on.

### Describe the proposed solution

Add an option to have the inspector auto-disable itself after opening something in the IDE. 

This behavior should not be the default, as it would make opening multiple components at once very tedious. But, people often only open one component at a time, so having an option to avoid being sent back to the IDE by accident would be nice.

### Alternatives considered

Simply stop forgetting the inspector is still on

### Importance

nice to have

**Comment by dominikg** [comment]
as a workaround you can try `holdMode: true`, that disables automatically when you release the combo.

I'd love to avoid having too many options, inspector has so many already. But agree that the described behavior can be frustrating.

**Comment by probablykasper** [comment]
The devtools inspector already works this way, and imo it should be the default behavior

**Comment by probablykasper** [comment]
Hold mode doesn't seem to help with this problem. When I click an element with hold mode, the inspector stays open even after letting go of the keys
