### ISSUE TITLE
Inspector - open parent component

### ISSUE THREAD

**Issue by ToP29** [sveltejs/vite-plugin-svelte#531]
### Describe the problem

If I have a button and i open it with inspector, it opens the button component, but usually I dont care about the button component, but about component where the button is used.

### Describe the proposed solution

If i click on component with inspector, i could get list of parents for this component and i could click on one of them to open them instead. It would open parent component on line, where selected component is used.
Inspector could have current behavior on left click and this more advanced one could be on right click.

### Alternatives considered

-

### Importance

would make my life easier

**Comment by dominikg** [comment]
you can use the up arrow key to select the parent component

**Comment by dominikg** [comment]
@ToP29  does arrow selection help with your usecase?

**Comment by ToP29** [comment]
Yes, it is ok. Thank you
