### ISSUE TITLE
Inspector: Can't get to owner of nested component if the owner only contains the component

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [sveltejs/vite-plugin-svelte#545]
### Describe the bug

In the inspector I can't get to the owner of nested component when hovering if the owner only contains the component.

Maybe it's supposed to be like that but I would like to be able to get to the owning component because I had set props there (not showing that in the repro example though).

In my real project I see 
```html
<!--<P>-->
<!--<OwningComponent>-->
```

in the devtools element list but maybe the inspector doesn't use those?

### Reproduction URL

https://stackblitz.com/edit/vitejs-vite-jwrile?file=src/lib/NestingP.svelte

### Reproduction

1. Click the inspector button.
2. Hover over the text "I am nested". It takes you to P.svelte even though the text "I am nested" comes from NestingP.svelte
3. Hover over the text "Unless I do something like this". It takes you to NestingP.svelte as expected because it has an element that is not another component.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^2.0.0 => 2.0.1 
    svelte: ^3.54.0 => 3.54.0 
    vite: ^4.0.0 => 4.0.0 

(... stackblitz)
```

**Comment by dominikg** [comment]
does using the up arrow for parent selection work for you?  also see https://github.com/sveltejs/vite-plugin-svelte/issues/531#issue-1484994739

**Comment by henrikvilhelmberglund** [comment]
No, it gives App.svelte instead of NestingP.svelte. So basically if there's a nested component but nothing else in the parent component it's not detected at all.

**Comment by dominikg** [comment]
oh, in that case the component is not selectable with the current implementation of svelte-inspector. 

The information which file/position to open is attached to dom nodes and svelte inspector finds them. No dom node, no find.

We could look into the possibility of scanning for comment nodes too but that could get tricky. Going to mark this as edge-case. It may ultimately need help from svelte compiler to get fixed.

**Comment by dominikg** [comment]
svelte inspector can only inspect components that have a representation in the dom, thats the nature of a dom inspector.

While we could try to leverage knowledge of the template structure and import graph to see if there are renderless components in between, you'd only be able to select them with special keyboard navigation. A different tool that shows you how components are nested as part of svelte devtools could be more fruitful to achieve this.

That would have to be planned/started there, inspector can only work with the data it has
