### ISSUE TITLE
Wrong file link format

### ISSUE THREAD

**Issue by jerrygreen** [sveltejs/vite-plugin-svelte#566]
### Describe the bug

Terminal file links have wrong format. It starts with `/`. It shouldn't. Gif:

![vscode-terminal-file-links-format](https://user-images.githubusercontent.com/13215662/209911267-9fa75af8-b5db-4a78-91dd-fa5327913255.gif)

- ❌ `/src/components/Search.svelte:41:6` doesn't work
- ✅ `src/components/Search.svelte:41:6` works

### Reproduction URL

(see gif)

### System Info

```shell
OS: Windows
```

**Comment by dominikg** [comment]
> Reproduction URL
A link to a repository or a fork of https://vite.new/svelte, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.
