### ISSUE TITLE
Rollup peer dependency

### ISSUE THREAD

**Issue by AleCandido** [sveltejs/vite-plugin-svelte#57]
## Description
Not a true bug, probably a not recommended dependency structure: 
```
@sveltejs/kit > @sveltejs/vite-plugin-svelte: @rollup/pluginutils@4.1.0 requires a peer of rollup@^1.20.0||^2.0.0 but none was installed.
``` 

## Reproduction
I just tried to use `pnpm` with `--strict-peer-dependencies` and it output the message above.

**Comment by dominikg** [comment]
vite-plugin-svelte only uses createFilter from pluginutils and it does not depend on rollup. it may be possible for pluginutils to mark the rollup peer dependency as optional

**Comment by Conduitry** [comment]
I don't think the concept of 'optional peer dependency' can be represented `package.json`, unfortunately.

I'm not sure how to get around this without having this plugin make `@rollup/pluginutils` a dev dependency instead and then bundle `createFilter` as part of its build process.

**Comment by dominikg** [comment]
with peerDependenciesMeta, pluginutils itself could. skimmed its source and it doesn't seem to use rollup, so while it is intended to be useful for rollup plugins and rollup will most likely be installed, it isn't technically required to have rollup for using pluginutils

**Comment by Conduitry** [comment]
Oh huh I didn't know about `peerDependenciesMeta` - it looks like it's a relatively new feature in npm. And it looks like pnpm has supported it for a while as well.

I could still certainly see the pluginutils maintainers not being interested in marking the peerdep as being optional, as it's certainly the more common case. Using pluginutils without using Rollup is probably fairly unusual. We could still always bundle the dependency then if this were a priority.

**Comment by dominikg** [comment]
i'm not really experienced with pre-bundling dependencies, would this mean we'd have to prebundle picomatch and possibly other dependencies of pluginutils aswell? I'd rather not do this and solve it within proper depdencency declarations.
vite has a dependency on rollup, so technically a version of rollup is already there. 
 
Another solution could be to fork rollup pluginutils to vite pluginutils...

How much of a problem is this warning really?

**Comment by bluwy** [comment]
FWIW Evan You has a history of pre-bundling dependencies in his projects. Vite also has [a guide on managing dependencies](https://github.com/vitejs/vite/blob/main/.github/contributing.md#notes-on-dependencies). Though, I personally prefer proper dependency declarations too.

We could try requesting pluginutils to add the `peerDepedenciesMeta` option, seems like a harmless addition. And it would indirectly help other rollup/vite plugins too.

**Comment by dominikg** [comment]
there is a PR already to remove that entirely on pluginutils https://github.com/rollup/plugins/pull/845

**Comment by dominikg** [comment]
unfortunately the PR on pluginutils still isn't merged, if this is important to you please add your thumbsup to it here: https://github.com/rollup/plugins/pull/845

**Comment by dominikg** [comment]
released https://github.com/sveltejs/vite-plugin-svelte/releases/tag/%40sveltejs%2Fvite-plugin-svelte%401.0.0-next.13
