### ISSUE TITLE
CSS module generates empty style

### ISSUE THREAD

**Issue by JeromeDeLeon** [sveltejs/vite-plugin-svelte#58]
## Description

It inserts the generated class name for every element under svelte file.
https://github.com/sveltejs/svelte-preprocess/issues/372

## Reproduction

_Inside the linked issue_

## Additional Information

System:
- OS: Windows 10 10.0.19042
- CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
- Memory: 6.88 GB / 15.87 GB

Binaries:
- Node: 14.17.0
- Yarn: 1.22.10
- npm: 6.14.13

Browsers:
- Chrome: 91.0.4472.101
- Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
- Internet Explorer: 11.0.19041.1

npmPackages:
- @sveltejs/vite-plugin-svelte: 1.0.0-next.11 => 1.0.0-next.11
- svelte: ^3.34.0 => 3.38.2
- vite: ^2.3.7 => 2.3.7

**Comment by dominikg** [comment]
this is on purpose and only applied during dev with hmr.
https://github.com/sveltejs/vite-plugin-svelte/blob/09b63d32e8816acc554a66d4d01062be197dfbb7/packages/vite-plugin-svelte/src/utils/preprocess.ts#L68

its a minor hack to prevent a svelte js optimization that would result in js hmr updates,when only css was edited.

does it happen during release build too or cause any problems for you?

the rule is empty so should not affect anything. cc @rixo

**Comment by JeromeDeLeon** [comment]
It didn't happen when building svelte but the explanation makes sense. I just got surprised when it suddenly add generated classes everywhere. Thanks for looking it up.
