### ISSUE TITLE
Enabling experimental `inspector` does nothing

### ISSUE THREAD

**Issue by FluffyDiscord** [sveltejs/vite-plugin-svelte#587]
### Describe the bug

Basically the title, nothing more to add

### Reproduction URL

https://stackblitz.com/edit/vitejs-vite-p8ax13?file=vite.config.js

### Reproduction

1. Open reproduction URL
2. Press CTRL + SHIFT
3. Nothing happens

### System Info

```shell
Windows, Firefox/Chrome
```

**Comment by dominikg** [comment]
The default keycombo for windows is   `meta-shift` but that does not work in firefox. 
 To use control-shift, you have to add  `toggleKeyCombo: 'control-shift'` to the inspector config.
 
 see https://github.com/sveltejs/vite-plugin-svelte/pull/555 which i havn't gotten around to yet :/

**Comment by FluffyDiscord** [comment]
The reproduction URL now works, but it still won't show up in my app. Are there any specific requirements for it to show up/work?

**Comment by dominikg** [comment]
did you remove the top level div and mount your app directly on document.body ? in that case it's possible that hydration removes the inspector element again.

**Comment by FluffyDiscord** [comment]
That would be the issue. Sadly I cannot do that due to my router, so my only option is to add it manually. Thank you for your time

**Comment by FluffyDiscord** [comment]
I am opening this issue since I have misread your answer. I do not mount my app directly to the `body`. It resides inside its own `div` and nothing is overwriting `body` since the app would not work at all.

![image](https://user-images.githubusercontent.com/10332247/223206134-45c1b475-0cba-43e0-9665-9d47c399fb27.png)

**Comment by bluwy** [comment]
The latest version now mounts the inspector to the Vite client, which should always work now. Please open a new issue if you're seeing an issue again. Thanks!
