### ISSUE TITLE
failed to load config from vite.config.js

### ISSUE THREAD

**Issue by lapwat** [sveltejs/vite-plugin-svelte#59]
## Description

Failed to load config when building.

## Reproduction

```sh
yarn create @vitejs/app failed-to-load-config --template svelte-ts
cd failed-to-load-config
yarn
yarn dev
```

Error:

```sh
failed to load config from /tmp/failed-to-load-config/vite.config.js
error when starting dev server:
```

**Comment by dominikg** [comment]
unfortunately the lastest breaking change in vite-plugin-svelte required an update to vites template. that was merged but not released 

 see this PR on how to update your project locally
https://github.com/vitejs/vite/pull/3760

more info:
https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/CHANGELOG.md#sveltejsvite-plugin-svelte

**Comment by lapwat** [comment]
```js
import { svelte } from '@sveltejs/vite-plugin-svelte';
```

Works wellm thanks

**Comment by patak-js** [comment]
FYI, @vitejs/create-app v2.4.3 was just released including https://github.com/vitejs/vite/pull/3760

**Comment by manadinho** [comment]
check your node version, it must be greater than v14.

**Comment by Zephni** [comment]
I have node v16.17.1 but am still getting this error. I noticed @lapwat posted "import { svelte } from '@sveltejs/vite-plugin-svelte';" as a solution of some kind but even after looking at the links provided I'm not sure where to put this or what to do next. It seems strange that I'm getting this error in an out of the box Laravel 9 install with everything up to date.

**Comment by dominikg** [comment]
See https://github.com/sveltejs/vite-plugin-svelte#usage

Please note that this issue was raised a long time ago. Make sure you use the latest version of vite-plugin-svelte.
For questions how to integrate/use vite-plugin-svelte please use https://svelte.dev/chat `#questions`.It will be helpful if you provide a link to a repo with your setup when asking there.

**Comment by CodeLeom** [comment]
> @Zephni 

you can put that in your vite.config.js

**Comment by anroche** [comment]
I have this issue because a try to setup a monorepo, but i don't pay attention a don't o have the same node version to my root package.json and in one of my package/workspace.

Pay attention to the versions of node you are using
