### ISSUE TITLE
unused css selector

### ISSUE THREAD

**Issue by craigcosmo** [sveltejs/vite-plugin-svelte#596]
### Describe the problem

I got a bunch of warning like this in the consle terminal, how to disable those css warning ?

<img width="943" alt="Screenshot 2023-02-22 at 9 55 25 AM" src="https://user-images.githubusercontent.com/538657/220509647-26ce3e15-45c1-4da6-bbcf-e18c1e12746c.png">

### Describe the proposed solution

disable it 

### Alternatives considered

remove it ?

### Importance

i cannot use vite-plugin-svelte without it

**Comment by bluwy** [comment]
https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#onwarn

Please ask for support in the Svelte discord server.
