### ISSUE TITLE
Expose sveltePreprocess API

### ISSUE THREAD

**Issue by eakl** [sveltejs/vite-plugin-svelte#607]
### Describe the problem

In my setup (monorepo + modified project root + tailwind), I need to access `postcss.configFilePath` from sveltePreprocess as recommended [here](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/other-css-preprocessors.md)

```js
export default {
    preprocess: sveltePreprocess({
        postcss: {
            configFilePath: join(__dirname, 'postcss.config.cjs')
        }
    })
};
```

As mentioned [here](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md) I could do this

```js
// svelte.config.js
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import sveltePreprocess from 'svelte-preprocess';

export default {
  preprocess: [
    vitePreprocess({ style: false }),
    sveltePreprocess({
      postcss: {
        configFilePath: join(__dirname, 'postcss.config.cjs')
      }
    })
  ]
};
```

What is the impact of doing `vitePreprocess({ style: false })` and adding `sveltePreprocess` on top with just the `postcss` option as above?

- Will it keep `vitePreprocess`'s defaults regarding `script` and delegate `style` to `sveltePreprocess` or `sveltePreprocess` is overriding `vitePreprocess` completely?
- Will it override all `vitePreprocess`'s defaults regarding `style` (SASS, SCSS...) or just PostCSS?

I would like to override PostCSS settings with `sveltePreprocess` but keep every other defaults (Typescript, esbuild, SASS, SCSS) from `vitePreprocess`.

### Describe the proposed solution

Could we just expose `sveltePreprocess` API and override `vitePreprocess`'s defaults with options passed to `vitePreprocess`?

### Alternatives considered

More granular fine tuning

### Importance

i cannot use vite-plugin-svelte without it

**Comment by bluwy** [comment]
> * Will it keep `vitePreprocess`'s defaults regarding `script` and delegate `style` to `sveltePreprocess` or `sveltePreprocess` is overriding `vitePreprocess` completely?

Yes `vitePreprocess` will continue to work on `scripts` and not on `style`. `sveltePreprocess` will work on the `style` only.

> * Will it override all `vitePreprocess`'s defaults regarding `style` (SASS, SCSS...) or just PostCSS?

`sveltePreprocess` will override all of `vitePreprocess` `style` handling as `vitePreprocess` doesn't handle `style` anymore.

---

You could also pass the postcss config to https://vitejs.dev/config/shared-options.html#css-postcss and keep using `vitePreprocess` too?

**Comment by dominikg** [comment]
vite uses postcss-load-config, so it should be able to pick up your postcss.config.cjs just fine. otherwise please use vite config as shown by @bluwy 

Not really sure what you are proposing here either, vitePreprocess delegates to vite, sveltePreprocess has its oen config too. You can use/configure both already, there is nothing we can expose in addition.

**Comment by eakl** [comment]
To give you more context,

I am using Vite + Svelte + Tailwind (via PostCSS). Svelte is complaining about Tailwind's complex classes inside the `<style>` tag (`hover:`, `focus:`, etc...)

Doing the following makes the VSCode extension complaining

```html
<style lang="postcss">
  .some-class {
    @apply border border-black bg-blue-500 hover:bg-red-500;
                                           ^^^^^
  }
</style>
```

```
.hover\:bg-red-500:hover {
  --tw-bg-opacity: 1;
  background-color: rgb(239 68 68 / var(--tw-bg-opacity));
}
Semicolon or block is expected

If you expect this syntax to work, here are some suggestions: 
If you use less/SCSS with `svelte-preprocess`, did you add `lang="scss"`/`lang="less"` to your `style` tag? If you use SCSS, it may be necessary to add the path to your NODE runtime to the setting `svelte.language-server.runtime`, or use `sass` instead of `node-sass`. 
Did you setup a `svelte.config.js`? 
See https://github.com/sveltejs/language-tools/tree/master/docs#using-with-preprocessors for more info. svelte(css-syntax-error)
```

[svelte-vscode](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/in-general.md) needs to know how to process the `<style>` tag with postcss.

> If a svelte file contains some language other than html, css or javascript, svelte-vscode needs to know how to preprocess it. This can be achieved by creating a svelte.config.js file at the **root** of your project. It's recommended to use the official svelte-preprocess package.

Because my `svelte.config.js` is not located at the root of the project but in a workspace (I am using a monorepo), I need to reference the config file in the svelte processor (see [here](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/other-css-preprocessors.md#postcss))

```ts
export default {
    preprocess: sveltePreprocess({
        postcss: {
            configFilePath: join(__dirname, 'postcss.config.cjs')
        }
    })
};
```

The problem raised in my previous post is that `vitePreprocess` doesn't expose the `postcss.configFilePath` and using `sveltePreprocess` cancel other `vitePreprocess` defaults regarding `style` (SASS, SCSS etc.)

Doing this works but it cancels other `style` defaults

```ts
// svelte.config.js
export default {
  preprocess: [
    vitePreprocess({ style: false }),
    sveltePreprocess({
      postcss: {
        configFilePath: resolve(__dirname, './postcss.config.cjs')
      }
    })
  ]
}
```

And @bluwy suggestion doesn't solve the issue.

I think the `postcss.config.cjs` path needs to be passed to the sveltePreprocessor and `vitePreprocess` doesn't allow it.

**Comment by bluwy** [comment]
The docs for [vitePreprocess](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md#vitepreprocess) mentions that you can pass Vite inline config to `style` option too, so:

```js
export default {
  preprocess: [
    vitePreprocess({
      style: {
        css: {
         postcss: resolve(__dirname, './postcss.config.cjs')
        }
      }
    })
  ]
}
```

Another way, if you have a `vite.config.js`, is by

```js
import { resolveConfig } from 'vite'

export default {
  preprocess: [
    vitePreprocess({
      style: resolveConfig({ configFile: '..path-to-vite-config' })
    })
  ]
}
```

**Comment by dominikg** [comment]
This repository and issue tracker is for vite-plugin-svelte only. As mentioned above, you can configure both svelte-preprocess or vitePreprocess through their respective configs, including a custom path for the postcss config file.

In regular setups, postcss-load-config should be able to detect your postcss.config.cjs just fine, no extra config needed. In custom setups lik yours, you are responsible for passing in that config.

Note that the docs in svelte languagetools repo you are referring to use `__dirname` and only apply to commonjs setups. They do not apply to vite+svelte.

I'm going ahead and close this as there is not an actionable feature request here. The configuration options you ask for already exist. 
If you have a problem setting them up correctly, please use https://svelte.dev/chat and ask in `#svelte-and-kit`
If you have set it up correctly and the vscode extension or language-tools show an error where there shouldn't be one, please file an issue in the responsible repository and include a reproduction.

**Comment by ccll** [comment]
After struggling for a day I finally found this thread, with the info from this thread I solved the `Semicolon or block is expected` issue with vitePreprocess().

Thanks guys, really appreciate your help, and I'll leave a detailed instruction for future reference if anyone find it useful later.

The main problem is that when using a multi-root workspace project in vscode, the postcss and tailwind config will not properly load.

We need to explicitly specify the config files, in 3 places.

```js
// subdir/svelte.config.js

// Get `__dirname` in ESM.
import path from "path";
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const config = {
    ...
    preprocess: [
        vitePreprocess({
            style: {
                css: {
                    postcss: path.resolve(__dirname, './postcss.config.cjs')
                }
            }
        }),
    ],
    ...
}
```

```js
// subdir/vite.config.js
export default defineConfig({
   ...
   css: {
        postcss: path.resolve(__dirname, './postcss.config.cjs'),
    },
   ...
})
```

```js
// subdir/postcss.config.js

const config = {
    plugins: [
        tailwindcss(path.resolve(__dirname, './tailwind.config.cjs')),
        autoprefixer,
    ],
};
```

That's all, now restart vscode or svelte language server, problem solved.

Note that we can directly specify the postcss plugin list in `svelte.config.js` and `vite.config.js`, thus we don't need a separate `postcss.config.js` file, but I found that vite config will complain about incompatibility type between Plugin (the autoprefixer return type) and AcceptedPlugin (the postcss plugin list accepted type), so a separate `postcss.config.js` file works better here.
