### ISSUE TITLE
Failed Build on Netlify

### ISSUE THREAD

**Issue by zommerberg** [sveltejs/vite-plugin-svelte#61]
Hello! 
From v11 I get the following error when trying to deploy to netlify:

```
(node:65589) UnhandledPromiseRejectionWarning: file:///.../node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:214
import { createMakeHot } from "svelte-hmr";
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'svelte-hmr' does not provide an export named 'createMakeHot'
```

Other people reported the same issue with github pages.

Downgrading to v10 manually solves the problem.

**Comment by sebastinez** [comment]
Yes I have the same issue on v11 and on v10 it seems there is another issue
```
import { svelte } from "@sveltejs/vite-plugin-svelte";
         ^^^^^^
SyntaxError: The requested module '@sveltejs/vite-plugin-svelte' does not provide an export named 'svelte'
```

Any idea to which version we should change?

**Comment by bluwy** [comment]
v11 now includes an ESM bundle and uses named export `svelte` instead of a default export in v10, but the underlying package `svelte-hmr` only exports CJS, which I believe caused the underlying `createMakeHot` error.

I'm not sure how easy it would be to have `svelte-hmr` provide an ESM bundle, but otherwise we could make a change in vite-plugin-svelte to import with `import * as svelteHmr as "svelte-hmr` to bypass the issue.

**Comment by dominikg** [comment]
thanks for reporting this. The tests with adapter-static still worked so this slipped through :/

I wonder whats going on here though, svelte-hmr shouldn't be part of final build output as it is only used for hmr during dev.
As a workaround you could downgrade to -next.10 and use the default export again ( see https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/CHANGELOG.md#major-changes )

**Comment by bluwy** [comment]
IIRC node had issues in importing named imports of CJS files that do named exports. But I can't reproduce on my side too, could be related to the node version used? A repro would be great @zommerberg

**Comment by zommerberg** [comment]
@bluwy I can reproduce it only when I try to deploy it. Building it locally doesn't throw an error. The default sveltekit project should be able to reproduce it.

**Comment by sebastinez** [comment]
> v11 now includes an ESM bundle and uses named export `svelte` instead of a default export in v10

This solved my issue thank you @bluwy!

**Comment by bluwy** [comment]
@zommerberg Is the netlify deploy log public? Would be nice to see when/how it fails. The log should also show the node version, which I'm guessing it could be that an older node version was used that caused the error, the minimum supported node version for vite-plugin-svelte  is v12,

**Comment by dominikg** [comment]
yes, please share a full log and a minimal reproduction. I think you're able to select a node version in netlify by adding a `.nvmrc`file.

**Comment by dominikg** [comment]
according to this https://github.com/sveltejs/kit/pull/1517#issuecomment-862965387 ,  you have to update your project to match the sveltekit template and add a . node-version file that tells netlify to use a compatible version. 
https://github.com/sveltejs/vite-plugin-svelte/blob/09b63d32e8816acc554a66d4d01062be197dfbb7/package.json#L80

**Comment by zommerberg** [comment]
@dominikg  I can confirm that manually setting the node version to `v14.17.0` solves the problem. 

As far as the old log goes:

```
11:44:00 PM: $ npm run build
11:44:00 PM: > hamster-app@0.0.1 build /opt/build/repo
11:44:00 PM: > svelte-kit build
11:44:00 PM: (node:1356) ExperimentalWarning: The ESM module loader is experimental.
11:44:00 PM: > The requested module 'svelte-hmr' does not provide an export named 'createMakeHot'
11:44:00 PM: file:///opt/build/repo/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:214
11:44:00 PM: import { createMakeHot } from "svelte-hmr";
11:44:00 PM:          ^^^^^^^^^^^^^
11:44:00 PM: SyntaxError: The requested module 'svelte-hmr' does not provide an export named 'createMakeHot'
11:44:00 PM:     at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
11:44:00 PM:     at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
11:44:00 PM:     at async Loader.import (internal/modules/esm/loader.js:179:24)
11:44:00 PM:     at async file:///opt/build/repo/node_modules/@sveltejs/kit/dist/cli.js:645:22
```

**Comment by dominikg** [comment]
thanks
