### ISSUE TITLE
Update to Typescript 5 ?

### ISSUE THREAD

**Issue by nielk** [sveltejs/vite-plugin-svelte#610]
### Describe the problem

 I can't update typescript on my project because vite-plugin-svelte does not support it.

### Describe the proposed solution

Could you update vite-plugin-svelte to support typescript 5.0.x ?

### Alternatives considered

Create a `@beta` tag for typescript 5 ?

### Importance

i cannot use vite-plugin-svelte without it

**Comment by bluwy** [comment]
vite-plugin-svelte doesn't depend on a specific version of TypeScript. Please elaborate what didn't work.

**Comment by nielk** [comment]
Hello,
Thanks for the quick reply. Yes something was wrong with my config, it was not due to vite-plugin-svelte. I'm closing this issue.
