### ISSUE TITLE
Error message doesn't have file or line number

### ISSUE THREAD

**Issue by benmccann** [sveltejs/vite-plugin-svelte#62]
## Description

Using SvelteKit, I got the error message:
```
Expected }
ParseError: Expected }
```

It doesn't tell me what file or line number. I wasn't quite sure, which project to file this under. Hopefully I got it right, but if not we can transfer to another repo

## Reproduction

Add the invalid `.svelte` file below to your project

```
<script>
	export let src;
	export let alt;
	export let width;
	export let height;
</script>

{#if typeof src === 'string'}
	<img {src, alt, width, height} />
{:else}
	<picture>

	</picture>
{/if}
```

## Additional Information

- SvelteKit 1.0.0-next.110
- vite-plugin-svelte 1.0.0-next.10
- svelte 3.38.2
- vite 2.3.3

**Comment by bluwy** [comment]
I'm able to reproduce this in SvelteKit, but not in a pure Vite + Svelte template, as the stacktrace is properly shown:
![image](https://user-images.githubusercontent.com/34116392/122342932-c0584400-cf77-11eb-89b5-f9b2e42e713e.png)
![image](https://user-images.githubusercontent.com/34116392/122343011-d403aa80-cf77-11eb-8741-acab60d60ca9.png)

It could be a Vite-related issue as SvelteKit seems to be using [vite.ssrFixStacktrace](https://github.com/sveltejs/kit/blob/1c78dec3b65d407db70a555ff54cc11442dcdc07/packages/kit/src/core/dev/index.js#L335).

**Comment by bluwy** [comment]
Actually, I found that Vite attaches custom properties to the Error object, which can be used to show the complete error similar to the images above. [Here's how the Vite client does it](https://github.com/vitejs/vite/blob/74d409eafca8d74ec4a6ece621ea2895bc1f2a32/packages/vite/src/client/overlay.ts#L125-L144).

SvelteKit could adapt a similar approach to print out these custom properties as well.

**Comment by dominikg** [comment]
i added compiler warning output to next.11 https://github.com/sveltejs/vite-plugin-svelte/pull/45

not sure it helps with the error case but if it helps we could try to catch the compiler error and produce a similar message out of it? Handling compiler errors in a user friendly way is definetely something i'd rather have in vite-plugin-svelte than sveltekit

**Comment by benmccann** [comment]
> It could be a Vite-related issue as SvelteKit seems to be using vite.ssrFixStacktrace.

I'm not seeing that line called, though [this one is](https://github.com/sveltejs/kit/blob/6ace879521cff9125a5ee748103a710b8f558786/packages/kit/src/core/dev/index.js#L211). `ssrFixStacktrace` seems to be having no effect. I think the stack trace is essentially correct. The issue is that the stack trace isn't really useful. We want to know where the compiler failed - not how it was called.

If I print `error.id` it will tell me the file, which is a pretty good start. It looks like there's also supposed to be an `error.loc` to give the line number, which I don't see though:

https://github.com/vitejs/vite/blob/74d409eafca8d74ec4a6ece621ea2895bc1f2a32/packages/vite/src/client/overlay.ts#L136

I would expect that `error.loc` is something that `vite-plugin-svelte` is supposed to provide since it's calling the compiler

**Comment by benmccann** [comment]
It looks like `loc` and `frame` specification is from Rollup and Vite leverages them

https://rollupjs.org/guide/en/#onwarn

**Comment by benmccann** [comment]
Hmm. Actually, maybe in the case I've run into right now the bug is actually in the Svelte compiler. Most of what I said above is probably still true except the one thing I question is whether `error.loc` actually is unset. I should test on another example as I expect it normally may be

**Comment by benmccann** [comment]
This is an issue in SvelteKit. I can't transfer the issue there so I'll just close this one. I'm sending a PR to fix it
