### ISSUE TITLE
Restart Vite server on svelte config file change 

### ISSUE THREAD

**Issue by bluwy** [sveltejs/vite-plugin-svelte#63]
**Describe the feature**
When updating `svelte.config.js`, it will restart the Vite dev server,

**A Usecase**
Convenient if this is handled automatically.

**Alternatives**
Manually restart dev server.

**Additional context**
This is how [vite-plugin-windicss handles](https://github.com/windicss/vite-plugin-windicss/blob/6324d294db73a6033bee407bca8c4610dc87f404/packages/vite-plugin-windicss/src/index.ts#L86-L94) currently.

I think it would be a simple addition, but I have concerns if this could negatively affect SvelteKit.

**Comment by dominikg** [comment]
alternative idea: instead of restarting the server one could trigger change events on all known compiled files like done for preprocessor dependencies https://github.com/sveltejs/vite-plugin-svelte/blob/09b63d32e8816acc554a66d4d01062be197dfbb7/packages/vite-plugin-svelte/src/utils/watch.ts#L14

**Comment by bluwy** [comment]
Sounds good too if it proves to be a stable approach :+1:

**Comment by dominikg** [comment]
had a closer look at this and i'm not sure if it's worth pursuing this feature. Editing svelte config while the server is running should be rare and a complete restart is required to make it work.

Problems: 
- the whole svelte config load+resolve has to rerun and this is currently split between the config and configResolved hooks
- it is possible that a svelte config change results in a vite config change and there is no way to change that in a running instance
- cache state could become inconsistent in vite

The only guaranteed safe way to do it is to restart `vite dev`.  We could issue a warning in form of a log (or an error message via websocket that turns into an overlay?) so users can decide if they want to continue or restart.

**Comment by dominikg** [comment]
there is a PR to add a restart cli shortcut: https://github.com/vitejs/vite/pull/3182   
if/when that lands we could try to send the shortcut to process.stdin on svelte config change or try to make restart accessible for plugins

**Comment by bluwy** [comment]
Thanks for looking into this. I just realized that I sent the wrong code for windicss's restart handling, apparently that reloads the browser only.

vite-plugin-restart's [restart trick](https://github.com/antfu/vite-plugin-restart/blob/d8d5b9de7f2197ca1d8604597e380bd207203437/src/index.ts#L105) was actually what I was going for. It simulates a vite config change update, which triggers Vite to restart the server.

**Comment by dominikg** [comment]
somehow i failed to find the code where vite restarts the server when its config changes. See #74 for an initial implementation

**Comment by bluwy** [comment]
The restart server code should be [here](https://github.com/vitejs/vite/blob/7362e6e9a7a0f0177b467f1cf80552acf22c46a0/packages/vite/src/node/server/hmr.ts#L63), it's called before plugins' `handleHotUpdate` hook.
