### ISSUE TITLE
vite inspector does not open a file when using turborepo

### ISSUE THREAD

**Issue by nzaero** [sveltejs/vite-plugin-svelte#684]
### Describe the bug

i am using turborepo, sveltekit project 
	vitePlugin: {
		inspector: true
	},

this does not open the file
any idea why ? 
also interested to verify with the behavior : Turborepo + VSCODE workspaces... but at least it does not work with turbo repo, it does not open the file, but it gives the good file's path

### Reproduction URL

i am using turborepo, svelte

### Logs

```shell
-
```

### System Info

```shell
-
```

**Comment by bluwy** [comment]
Please provide a repro

**Comment by dominikg** [comment]
we can revisit this if you provide the required information, for now closing this as invalid
