### ISSUE TITLE
Cannot change Vite dev server URL for inspector

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/vite-plugin-svelte#685]
### Describe the bug

When using a separate server that [Vite has been integrated into](https://vitejs.dev/guide/backend-integration.html#backend-integration), the `open-in-editor` command will always be sent to the wrong address.

The plugin uses the Vite config `base` to determine where to send the command but even if a full URL is specified, e.g.
```js
export default defineConfig(() => ({
  plugins: [svelte()],
  base: 'http://localhost:3001/wah',
  server: { port: 3001, strictPort: true },
}));
```

Vite normalizes it, and everything except the path gets removed, this is how the above resolves [in the plugin](https://github.com/sveltejs/vite-plugin-svelte/blob/32284be3dc105b762c9bb370e46ce7a8cef49933/packages/vite-plugin-svelte-inspector/src/index.js#L67C11-L67C11):

![image](https://github.com/sveltejs/vite-plugin-svelte/assets/834235/76245f02-f7b7-482d-ac2d-d1817fde577e)

With the application running on a different port from the Vite dev server, this leads to the `open-in-browser` command being sent to the wrong endpoint.

The plugin probably should take Vite's `server` options into account to make sure the correct port is used or offer a way to explicitly set the endpoint (though that would lead to redundancy on the side of the user).

### Reproduction URL

https://github.com/brunnerh/vite-plugin-svelte-inspector-port-issue

### Reproduction

Run scripts in two *separate* terminals:

```shell
npm run server
npm run vite
```

Open http://localhost:3000 in your browser.

Ctrl + Shift click an element on the page.

Observe `__open-in-editor` command being sent to `http-server` rather than `vite`.

### Logs

Requests to `http-server`:
```shell
[2023-07-07T08:42:31.783Z]  "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
[2023-07-07T08:42:32.162Z]  "GET /src/assets/vite.svg" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
[2023-07-07T08:42:32.166Z]  "GET /src/assets/svelte.svg" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
[2023-07-07T08:44:09.458Z]  "GET /__open-in-editor?file=src%2FApp.svelte%3A8%3A3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
[2023-07-07T08:44:09.459Z]  "GET /__open-in-editor?file=src%2FApp.svelte%3A8%3A3" Error (404): "Not found"
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 6.83 GB / 31.69 GB
  Binaries:
    Node: 18.16.0 - ~\AppData\Local\Programs\NodeJS\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\Programs\NodeJS\yarn.CMD
    npm: 9.5.1 - ~\AppData\Local\Programs\NodeJS\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^2.4.2 => 2.4.2
    svelte: ^4.0.3 => 4.0.4
    vite: ^4.4.0 => 4.4.1
```

**Comment by dominikg** [comment]
The vite client itself also uses config.base from resolved config: https://github.com/vitejs/vite/blob/abf536f920c32db1b96f6b4cabb510281e5170f5/packages/vite/src/node/plugins/clientInjections.ts#L27

not only having an absolute base but also running 2 servers and loading the vite client from the other one is quite an uncommon setup. I think for complete integration of vite, you are responsible for forwarding __openInEditor requests from that server to the vite devserver instance. (this would work ootb if you loaded vite as a middleware into eg express)

**Comment by brunnerh** [comment]
Of course Vite uses the base, but it's just a path; if you look at the surrounding lines, it uses the `server` config to build a full URL:

```js
 const resolvedServerHostname = (await resolveHostname(config.server.host))
        .name
const resolvedServerPort = config.server.port!
const devBase = config.base

const serverHost = `${resolvedServerHostname}:${resolvedServerPort}${devBase}`
```

I think the inspector should do the same.

---

This kind of dual setup is unfortunately required for any incompatible backend; in my case the server is ASP.NET-based. Just migrating large, existing applications to Node is often not viable, so I do not think this should be considered an edge-case.

(Of course it would not make much sense to use `http-server` in conjunction with Vite like in my reproduction example.)

**Comment by dominikg** [comment]
devBase is used to [replace __BASE__](https://github.com/vitejs/vite/blob/abf536f920c32db1b96f6b4cabb510281e5170f5/packages/vite/src/node/plugins/clientInjections.ts#L72) in the [overlay](https://github.com/vitejs/vite/blob/4159e6f271b06f2253f08974d7eea80e2e7f32b0/packages/vite/src/client/overlay.ts#L6)
where it is then [prepended](https://github.com/vitejs/vite/blob/4159e6f271b06f2253f08974d7eea80e2e7f32b0/packages/vite/src/client/overlay.ts#L196). 

the code you showed is used by the vite devserver itself, not to reference the __openInEditor endpoint later on.

**Comment by brunnerh** [comment]
Oh, that looks like a bug then. I have never actually interacted with that overlay before.
I should test that and report an analogous issue in Vite if the links break in a scenario where the dev server is integrated instead of stand-alone.

**Comment by bluwy** [comment]
Yeah we're following with Vite behaviour here. I don't think it's a bug in Vite either because the `base` is not always used to configure your local URL, but also for the prod domain, which is often added like `base: "https://foo.github.io/project"`. So fixing this would break those projects.

The best workaround for now is to setup a proxy to redirect `/__open-in-editor` requests to Vite. I don't think a new option is needed here.

**Comment by iltimasd** [comment]
Bumping this as I am facing similar issue. It's not realistic for my app to proxy the open-in-editor requests as my app lives inside another. Would the maintainers be open to adding an "overrideBaseUrl" option to the plugin?

**Comment by dominikg** [comment]
https://github.com/sveltejs/vite-plugin-svelte/issues/685#issuecomment-1628387095 still stands

no plans to introduce an option that serves a very low number of users and has a reasonable workaround (which would also be needed to make the vite error overlay stacktrace links work btw)

**Comment by brunnerh** [comment]
The origin of the stack trace links have been fixed after I reported the problem (vitejs/vite/issues/13770), they now use `import.meta.url` as base argument for the constructed `URL`. Tried this fix for the inspector and it would also lead to the correct origin.

I also would not exactly call it "reasonable" to be required to integrate proxying into an application to work around a bug in a development-only tool. This is especially true if you have a bunch of different applications.

**Comment by dominikg** [comment]
svelte inspector has been built to be used within a vite devserver. Custom servers can be expected to provide the same environment as said devserver, or risk not having working tools not built for their custom server. We cannot service all custom integrations out there. If there is a fix for this that does not require adding an option and it keeps working in regular dev server use, i am happy to accept a PR. otherwise it is the responsibility of the custom server to provide the environment needed.
