### ISSUE TITLE
Multi-line comment breaks sourcemaps(?) (chrome debugging)

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [sveltejs/vite-plugin-svelte#705]
### Describe the bug

BROKEN:
```svelte
<script>
    /**
     * Start page for the app
     */
    console.log('Hiiiii');
```

OK:
```svelte
<script>
    console.log('Hiiiii');
    /**
     * Start page for the app
     */
```

OK:
```svelte
<script>
    // Start page for the app
    console.log('Hiiiii');
```

If your file starts with a multiline comment these are symptoms:

* that file appears as empty file in chrome devTools
* console logs still indicate the correct file line though
* Another file (duplicate?) has an error message:
  * `Could not load content for http://localhost:8000/Index.svelte (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)`
  
 
(Not sure how to properly describe this issue)

OK
![1](https://github.com/sveltejs/vite-plugin-svelte/assets/51773923/fc65afe6-80cd-40dd-8d94-9bc9de45229b)

BROKEN
![2](https://github.com/sveltejs/vite-plugin-svelte/assets/51773923/63a92974-d56a-4415-a8dd-33c054f20921)
![3](https://github.com/sveltejs/vite-plugin-svelte/assets/51773923/7bfe4262-53fa-4096-b575-b66c260901ab)

### Reproduction URL

https://github.com/

### Reproduction

If someone tries putting a multi-line comment at the top of one of their svelte files and it works fine, I'll chalk it up to my setup and I'll close this issue asap!!

(Only reporting because it took me way too long to figure out it was the comment causing issues. -.-;;)

### System Info

```shell
Windows, but running everything in a linux container (docker)

package.json

    "dependencies": {
        "@ar-js-org/ar.js": "^3.4.5",
        "@sveltejs/vite-plugin-svelte": "^2.0.3",
        "@unseenco/taxi": "^1.2.2",
        "mapbox-gl": "^2.14.1",
        "svelte": "^3.57.0",
        "vite": "^4.3.2"
    },
```

**Comment by dominikg** [comment]
please provide a link to a minimal repository and instructions how exactly to reproduce this, using the latest version of svelte (svelte4) and vite-plugin-svelte.

**Comment by dominikg** [comment]
unable to reproduce, report is missing required information.
