### ISSUE TITLE
prefer svelte exports condition over svelte field for resolving libraries

### ISSUE THREAD

**Issue by dominikg** [sveltejs/vite-plugin-svelte#725]
### Describe the problem

We want to remove support for svelte field altogether at some point, take gradual steps to ensure existing libraries can update to not hit users with errors.

### Describe the proposed solution

Start prefering the exports condition value over svelte field, add a more persistent/pressing warning for libraries that only use svelte field to switch to exports.

In a following major, drop svelte field resolve entirely. (possibly together with adding svelte 5 support)

### Alternatives considered

give it more time.

### Importance

would make my life easier

**Comment by Miniontoby** [comment]
Hi, 

I would like to report that you guys should edit the IF statement used to show a warning when a package is still having the `svelte` field in the root of the `package.json` in addition to the `exports` condition.

On the FAQ it is said that:
> For backwards compatibility, you can keep the `svelte` field in addition to the `exports` condition. But make sure that both always resolve to the same files.

However there is a package `svelte-dnd-action` and using that package, we get the warning:

`The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.`

However it has the exports condition in combination with the svelte field:
https://github.com/isaacHagoel/svelte-dnd-action/blob/aa5e28d7a9da4210e671409e45ab9d17cdab21b4/package.json#L29

**Comment by dominikg** [comment]
@Miniontoby  please file an issue including a link to a repository with a reproduction.

in general i think the exports map of that package could be changed a bit to put "svelte" into the "import" condition, otherwise you might end up resolving it via exports.import.default instead of exports.svelte. (unfortunately in exports maps order is relevant and first matching entry "wins").

so
```json
    "exports": {
        ".": {
            "import": {
                "types": "./dist/index.d.ts",
                "default": "./dist/index.mjs"
            },
            "require": {
                "types": "./dist/index.d.ts",
                "default": "./dist/index.js"
            },
            "svelte": "./src/index.js"
        }
    },
```
    
should be
    
```json
    "exports": {
        ".": {
            "import": {
                "types": "./dist/index.d.ts",
                "svelte": "./src/index.js",
                "default": "./dist/index.mjs"
            },
            "require": {
                "types": "./dist/index.d.ts",
                "default": "./dist/index.js"
            },
        }
    },
```
    
    
note that removing keys from an exports map is a breaking change.
    
vite-plugin-svelte does not validate the right hand side of the exports condition. it only checks if there is a "svelte" key somewhere in the json structure of the exports map.

please also check your package type field, it looks like .js might currently be mistaken as commonjs.

https://publint.dev/svelte-dnd-action

**Comment by Miniontoby** [comment]
I might file an issue later this week, but yeah since this is the issue that introduced it, I thought it would fit here....


But yeah the code you linked to is used for showing the `packagesWithoutSvelteExportsCondition` message, however that is NOT what I get, it is the `The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.` message that I get/see.

The message that I see doesn't seem to appear anywhere here in this repo tho... Nor in the whole sveltejs org ([see this search](https://github.com/search?q=org%3Asveltejs+The+following+packages+use+a+svelte+resolve+configuration+in+package.json+that+has+conflicting+results+and+is+going+to+cause+problems+future.&type=code))
So idk if that might be because I am still using svelte v4 since if I update, then my other packages won't install... 


And btw the svelte-dnd-action is NOT my repo/package.

**Comment by dominikg** [comment]
oh, sorry for not looking at that message more closely.

This particular warning had been added in #510  and then removed again in #747  it is only present in vite-plugin-svelte@2. So the easiest way for you to avoid it is to upgrade to vite-plugin-svelte@3.

**Comment by Miniontoby** [comment]
Uhmmmm.... I don't even have `vite-plugin-svelte` installed at all. Nor does the `svelte-dnd-action` package has...

**Comment by dominikg** [comment]
`@sveltejs/kit@1` had a direct dependency on it, yes. you can update to kit@2 , that has a peerDependency on vite-plugin-svelte@3.

**Comment by dominikg** [comment]
that one is legit, the package doesn't have one. Please tell the author. For further help please check our discord on https://sveltej.dev/chat  channel `#help-svelte-and-kit`.
