### ISSUE TITLE
configFile setting doesn't seem to work with Yarn 2

### ISSUE THREAD

**Issue by joelmukuthu** [sveltejs/vite-plugin-svelte#73]
## Description

When using Yarn 2, the `configFile` setting doesn't work as intended. The config file seems to be imported but then is not used at all. 

## Reproduction

- Small reproduction repo: https://github.com/joelmukuthu/vite-plugin-svelte-yarn-2-config-file-bug

## Additional Information

- The output of `npx envinfo --system --npmPackages vite,svelte,svelte-hmr,@sveltejs/vite-plugin-svelte`:

```text
 System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    Memory: 1.15 GB / 11.41 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 2.4.2 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
```

- debug logs produced with `DEBUG=vite:vite-plugin-svelte yarn build`:

```text
   vite:vite-plugin-svelte additional vite config {
  optimizeDeps: {
    exclude: [
      'svelte/animate',
      'svelte/easing',
      'svelte/internal',
      'svelte/motion',
      'svelte/store',
      'svelte/transition',
      'svelte',
      'svelte-hmr/runtime/hot-api-esm.js',
      'svelte-hmr/runtime/proxy-adapter-dom.js',
      'svelte-hmr'
    ]
  },
  resolve: {
    mainFields: [ 'svelte', 'module', 'jsnext:main', 'jsnext' ],
    dedupe: [
      'svelte/animate',
      'svelte/easing',
      'svelte/internal',
      'svelte/motion',
      'svelte/store',
      'svelte/transition',
      'svelte',
      'svelte-hmr/runtime/hot-api-esm.js',
      'svelte-hmr/runtime/proxy-adapter-dom.js',
      'svelte-hmr'
    ]
  }
} +0ms
  vite:vite-plugin-svelte default options for production  {
  extensions: [ '.svelte' ],
  hot: false,
  emitCss: true,
  compilerOptions: { format: 'esm', css: false, dev: false, hydratable: true }
} +8ms
  vite:vite-plugin-svelte resolved options {
  extensions: [ '.svelte' ],
  hot: false,
  emitCss: true,
  compilerOptions: { format: 'esm', css: false, dev: false, hydratable: true },
  configFile: 'vite-plugin-svelte-yarn-2-config-file-bug/svelte.config.js',
  root: 'vite-plugin-svelte-yarn-2-config-file-bug/app',
  isProduction: true,
  isBuild: true,
  isServe: false
} +22ms
vite v2.3.8 building for production...
  vite:vite-plugin-svelte resolveId vite-plugin-svelte-yarn-2-config-file-bug/app/index.html +35ms
✓ 1 modules transformed.
Generated an empty chunk: "index"
rendering chunks (1)...  vite:vite-plugin-svelte transformIndexHtml <script type="module" crossorigin src="/assets/index.935273ac.js"></script>
<!DOCTYPE html>
<html>
  <body>
    foo
  </body>
</html>
 +190ms
dist/index.html                 0.13kb
dist/assets/index.935273ac.js   0.00kb / brotli: 0.00kb
```

**Comment by dominikg** [comment]
this seems to be an issue with yarn2 pnp linker. vite-plugin-svelte reads the configfile via dynamic import or require from it's absolute path: https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/src/utils/load-svelte-config.ts#L14

when you change the linker in .yarnrc.yml `nodeLinker: node-modules`, it works.

**Comment by Conduitry** [comment]
https://github.com/yarnpkg/berry/issues/638 Yarn 2's PnP linker does not work with ESM modules. They're working on it, but they need more features on Node's end first.

**Comment by dominikg** [comment]
yes, unless you have `type: module` in the nearest package.json it should be commonjs.  But for some reason yarn2 with pnp linker returns an empty object instead of throwing when you run `import('...svelte.config.js').then(...)`.
This prevents the require fallback from happening here https://github.com/sveltejs/vite-plugin-svelte/blob/97ee68c5106e58b2e7c4eb97e8cf7dd1c52bbfd3/packages/vite-plugin-svelte/src/utils/load-svelte-config.ts#L30

The code there is not optimal, a better detection of cjs vs mjs and validation of the loaded config would have at least provided a better error message in this situation, still the root cause is pnp linker doing sth shady (or it simply does not support importing an absolute path?).

**Comment by joelmukuthu** [comment]
Thanks for the response @dominikg.  I don't have `"type": "module"` in any package.json file so I suppose the underlying issue here is that Yarn 2 doesn't support ESM modules, as @Conduitry mentioned. All the same it seems to me that the import logic here https://github.com/sveltejs/vite-plugin-svelte/blob/97ee68c5106e58b2e7c4eb97e8cf7dd1c52bbfd3/packages/vite-plugin-svelte/src/utils/load-svelte-config.ts#L22-L29 could be removed and instead have that delegated to node's (or yarn's) resolver. The reason being that it's incomplete - you'd need to check `type` in package.json or analyse whether the .js file has an `export` clause. Perhaps using `import` directly is enough since the package requires Node.js >= v12.20.

Thanks again for your help and also thanks for working on this module :) Closing.
