### ISSUE TITLE
A $$restProps class treated as unused

### ISSUE THREAD

**Issue by pooledge** [sveltejs/vite-plugin-svelte#77]
**Describe the feature**
When passing a non-universal class to a component from parent, it's beed removed as unused

**A Usecase**
To be honest, I'm not sure, if there is a better workaround for this problem than wrapping a component into another element and passing those classes to it. If not, I'd like to avoid extra markup, as well as pre-defining all possible cases i.e. provide style all possible classes in the component itself i.e. keep separating styling contexts.

**Alternatives?**
I'd also like to know whether there are better pro-pattern ways to solve this, thank you!

Parent:
`<Cta class="landing-cta--top" />`

Child:
`<button class="{$$restProps.class}">Action</button>`

Console:
`Unused CSS selector ".landing-cta--top"`

**Edit 1** My workaround fails: `Unused CSS selector ".ctas--top > button:first-child"`
**Edit 2** Setting `:global(.landing-cta--top) {}` from parent works, but it kinda negates the cool concept of non-dripping styles, doesn't it?

**Comment by bluwy** [comment]
Duplicate of https://github.com/sveltejs/svelte/issues/2870#issuecomment-496023106 and wrong repo.

**Comment by pooledge** [comment]
Apologies.

> Duplicate of [sveltejs/svelte#2870 (comment)](https://github.com/sveltejs/svelte/issues/2870#issuecomment-496023106) and wrong repo.

Thank you and apologies.
