### ISSUE TITLE
Suppress "ignoring compiler output js change..." message unless debugging enabled

### ISSUE THREAD

**Issue by Radiergummi** [sveltejs/vite-plugin-svelte#803]
### Describe the problem

If code in a component doesn't functionally change, but has updates in whitespace after saving, the plugin will emit a message such as this:
```
10:50:22 AM [vite-plugin-svelte] ignoring compiler output js change for /path/to/component.svelte as it
is equal to previous output after normalisation
```

This happens frequently when you reformat your code, perhaps even automatically in your IDE, so the console will contain a lot of these.  
I appreciate tooling letting me know what happens, but this message is neither actionable nor relevant. Is there any reason to emit it at all, unless debugging is enabled?

### Describe the proposed solution

I would like to suppress this log output, unless verbose or debugging mode is explicitly enabled.

### Alternatives considered

I know this issue is a nitpick, but improving DX is always good :)

### Importance

nice to have

**Comment by dominikg** [comment]
This is a reasonable request, i think we can lower the loglevel of this to debug. Would you want to work on a PR implementing it? Should be very easy (find the log, change info to debug and add a changeset)
