### ISSUE TITLE
Packaged Monorepo - exports from packages are not available

### ISSUE THREAD

**Issue by ticup** [sveltejs/vite-plugin-svelte#841]
### Describe the bug

Hi, not 100% it belongs here, but my biggest guess it is related to this part of the chain.
we're actually trying to setup a typescript packaged monorepo with sveltekit in it as an app, but we've got the same issue with just vite.

We've setup the simplest case of mono repo:
- apps/svelte
- packages/core

workspace are defined in the package.json:
```
"workspaces": [
    "apps/*",
    "packages/*"
  ],
```

we name the packages/core @monorepo/core in package.json and then we import something from it in the svelte app:

```
import { foo } from "@monorepo/core";
```

Typescript go to works, the workspace linking works, but when we build the svelte app it gives the error "imported variable" is not  exported by "path to correct built file" as imported by ...:

```
RollupError: "foo" is not exported by "../../packages/core/build/index.js", imported by "src/entry-server.ts".
```

"../../packages/core/build/index.js:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
exports.foo = 42;
```

So it points to the correct built file, that file does contain the required export, but still it says it's not exported.

<img width="730" alt="Screenshot 2024-01-20 at 22 00 04" src="https://github.com/sveltejs/vite-plugin-svelte/assets/962776/b4487a14-119d-4d23-a683-95b599d39ac3">

We use npm workspaces to create the monorepo, but we've tried as well with pnpm workspaces and using turbo on top as well and always gives the same result.
We've created a minimal setup that allows to reproduce the problem.

Thanks so much in advance for looking into this.

### Reproduction URL

https://github.com/ticup/vite-monorepo

### Reproduction

1) clone repo
2) npm i
3) npm i -w apps/svelte
4) cd packages/core
5) npm run build
6) cd ../../apps/svelte
7) npm run build (or dev) 

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.59 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.0 - ~/.nvm/versions/node/v20.6.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v20.6.0/bin/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 108.1.46.140
    Chrome: 120.0.6099.234
    Safari: 17.0
```

**Comment by dominikg** [comment]
the export and import are not in a .svelte file, vite-plugin-svelte is not involved in resolving or the error message, so I'm not sure why you think this would be a bug in vite-plugin-svelte.

Does it work without vite-plugin-svelte and starts breaking when you add it?

I'd recommend using `"type":"module"` for all packages, but not sure if that improves things.

Please use `#help-svelte-and-kit` on https://svelte.dev/chat for help on how to set up monorepos with sveltekit apps.

**Comment by ticup** [comment]
@dominikg  Thanks for having a look.
It's not really clear to me yet what each component is responsible for exactly in the sveltekit chain, so I thought the svelte-plugin was responsible for chaining together all svelte files (.js and .ts included). 

At sveltekit they say to first reproduce using only vite + svelte, to see if it's sveltekit or vite, so I guess it's vite-related then, since I can reproduce using only that.

I tried setting type to module, but that doesn't change anything.
Posted in #help-svelte-and-kit , but no answer yet, so I'll wait some more.

I'll close it here, thanks again for your time.
