### ISSUE TITLE
support sass imports from node_modules

### ISSUE THREAD

**Issue by ruckc** [sveltejs/vite-plugin-svelte#854]
### Describe the problem

[sass] Can't find stylesheet to import.
  ╷
2 │   @import 'bootstrap/scss/bootstrap.scss';
  │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/routes/+layout.svelte.vite-preprocess.scss 2:11  root stylesheet
  

### Describe the proposed solution

In my +layout.svelte, I'd like to load global styling from bootstrap.  It would be nice if I could load node_modules sass/scss files like this:

```html
<style lang="scss">
@import 'bootstrap/scss/bootstrap.scss'
</style>
```

### Alternatives considered

Trying to avoid precompiled styles, so when theming variables are updated, the app is autoreloaded.

### Importance

would make my life easier

**Comment by dominikg** [comment]
it is not recommended to use the style tag in sveltw components to import global styles. see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#where-should-i-put-my-global-styles

for sveltekit you can import it in  `<script>` of your root +layout.svelte

**Comment by dominikg** [comment]
then maybe create a src/global.scss  and import that in your script tag. Again, you should not import all of bootstrap into scoped svelte style of layout.svelte

please use https://svelte.dev/chat #help-svelte-and-kit to ask for help

**Comment by ruckc** [comment]
Plugin: vite:css
  File: /home/user/project/src/routes/global.scss:1:9
  Error: Can't find stylesheet to import.
    ╷
  1 │ @import "bootstrap/scss/bootstrap";
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    src/routes/global.scss 1:9  root stylesheet
