### ISSUE TITLE
Named export 'svelteInspector' not found

### ISSUE THREAD

**Issue by richelleYoj** [sveltejs/vite-plugin-svelte#855]
### Describe the bug

This error happens when using `pnpm` and not happening when using `npm`

How to reproduce:
1. Execute `pnpm install`
2. Execute `pnpm dev`

This error happens:
![Screenshot 2024-02-10 161415](https://github.com/sveltejs/vite-plugin-svelte/assets/151523054/1cec09f2-8e37-4bc5-8e38-2384e01a120b)

### Reproduction URL

https://github.com/richelleYoj/svelte-practice

### System Info

```shell
Currently using this version:
"@sveltejs/vite-plugin-svelte": "^3.0.2",

pnpm: v8.15.1
```

**Comment by dominikg** [comment]
please update the reproduction url to point to your clone and ensure that it is a minimal reproduction.

the error message you posted is wrong, the package. json has type module https://github.com/sveltejs/vite-plugin-svelte/blob/fffb06741db7aa8832d01110ce6783870e4577ab/packages/vite-plugin-svelte-inspector/package.json#L10

**Comment by richelleYoj** [comment]
Hello @dominikg,
I have updated the description and figured that this error only happens when using `pnpm`. I have a fresh install of svelte in my repo to understand the problem. Thank you.

**Comment by dominikg** [comment]
I can't reproduce this. On stackblitz, pnpm installs and runs it just fine: 
https://stackblitz.com/github/richelleYoj/svelte-practice?file=README.md

And @sveltejs/vite-plugin-svelte-inspector is an esm only package. It's exports map explicitly only allows it to be imported with `import`, there is no `require` or `default`.

https://github.com/sveltejs/vite-plugin-svelte/blob/93d75303c0d7669713ece66c9d4a30c8cb786c4f/packages/vite-plugin-svelte-inspector/package.json#L14

No other user has reported this kind of problem before and the only tell i see is that you have a strange onedrive virtual path. Please try to put the project on a local harddrive (preferably c:) and try again.

**Comment by dominikg** [comment]
please use https://svelte.dev/chat `#help-svelte-and-kit` to ask for help identifying your problem.

**Comment by Nrosa01** [comment]
I'm having that same issue, but it seems it only happens with pnpm, with node it works fine
