### ISSUE TITLE
Escape should close svelte inspector

### ISSUE THREAD

**Issue by olehmisar** [sveltejs/vite-plugin-svelte#858]
### Describe the problem

Escape does not close svelte inspector

### Describe the proposed solution

Escape should close svelte inspector

### Alternatives considered

-

### Importance

would make my life easier

**Comment by dominikg** [comment]
needs a key check for escape here https://github.com/sveltejs/vite-plugin-svelte/blob/0c2695dfa3e6176e406b4aa145df01a441f45f1b/packages/vite-plugin-svelte-inspector/src/runtime/Inspector.svelte#L191

**Comment by dominikg** [comment]
fixed by #880
