### ISSUE TITLE
Option to disable scoped CSS class hash in dev mode

### ISSUE THREAD

**Issue by Keavon** [sveltejs/vite-plugin-svelte#872]
### Describe the problem

My project doesn't use Svelte's scoped CSS feature. In production builds, the CSS class hash is automatically not included in the DOM. However, in dev builds, my DOM is polluted with the distracting `s--vOfALaMv87z` hashes everywhere which makes it harder to use dev tools. Because of [this](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#why-cant-csshash-be-set-in-development-mode), I can't write a custom function that returns an empty string in dev mode. But I'd still find it very valuable to disable the CSS in dev mode anyways.

### Describe the proposed solution

x

### Alternatives considered

x

### Importance

would make my life easier

**Comment by dominikg** [comment]
using scoped styles is the norm and the custom cssHash is required for css-hmr to work reliably during dev.

If you are 100% sure you don't need it, you can disable it today by using the [dynamicCompileOptions](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#dynamiccompileoptions) feature (these are not validated again, so use at your own risk!)

```js
dynamicCompileOptions({ filename, compileOptions }) {
  return {cssHash: ()=>''}         
}
```

i'd rather not introduce a new option for it.

Note that svelte5 is going to have integrated support for hmr and changes how css scoping works.

**Comment by dominikg** [comment]
You can use pnpm patch to add `false &&` in this if https://github.com/sveltejs/vite-plugin-svelte/blob/ba4ac32cf5c3e9c048d1ac430c1091ca08eaa130/packages/vite-plugin-svelte/src/utils/compile.js#L77

Do you have `<style>` tags in your .svelte files? You said you don't use scoped styles so I'm a bit confused.
If you use `<style global>` or `:global`, you should move them into separate css files https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#where-should-i-put-my-global-styles

**Comment by Keavon** [comment]
Yeah, I use `<style lang="scss" global>` in all my components. I'd prefer to keep the styles in the same file. If I have to balance separate files for stylesheets versus living with the distracting hash in my DOM while working in dev mode, I'll unfortunately have to pick living with the hash. Thank you for helping explain the options though, I really appreciate it :)
