### ISSUE TITLE
Invalid selector exception in SCSS

### ISSUE THREAD

**Issue by shadow-identity** [sveltejs/vite-plugin-svelte#910]
### Describe the bug

Nested [child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator) `>` does not work in scss with Svelte5.
It does **not** crash with svelte 4 (sveltekit 2.5.7(@sveltejs/vite-plugin-svelte@3.1.0)(svelte@4.2.15)(vite@5.0.10) on my machine, but it does crash in the main [svelte REPL](2.5.7(@sveltejs/vite-plugin-svelte@3.1.0)(svelte@4.2.15)(vite@5.0.10)) app, which, I believe, uses svelte 4.

### Reproduction URL

https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE02OwQ7CIBBEf4Xs2aR3RBK_Qzxg2SpxuyUubWwa_l2oHrzNzNvM7AZDJBTQlw3YjwgazinBAfKampEFKWP1Ms2vviUmxMU6dtlI8mwf0XS7cGy6H2IjeSVU5Pl-ciC9iIMKKlabY6VClER-1WogfB9bYlUr-dI_fqOpf-4HxXFpE3uzrQ-NU4hDxAA6v2Ys1_IBYkJoa8sAAAA=

### Reproduction

Use [repl](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE02OwQ7CIBBEf4Xs2aR3RBK_Qzxg2SpxuyUubWwa_l2oHrzNzNvM7AZDJBTQlw3YjwgazinBAfKampEFKWP1Ms2vviUmxMU6dtlI8mwf0XS7cGy6H2IjeSVU5Pl-ciC9iIMKKlabY6VClER-1WogfB9bYlUr-dI_fqOpf-4HxXFpE3uzrQ-NU4hDxAA6v2Ys1_IBYkJoa8sAAAA=) or add this style to a component 
```scss
<style lang="scss">
div {
  display: flex;
  > span {
    display: block;
  }
}
</style>
```
Run the dev server, observe compilation error.

### Logs

```shell
[vite] 4:58:57 PM [vite] Internal server error: /Users/.../X.svelte:203:8 Invalid selector
[vite]   Plugin: vite-plugin-svelte
[vite]   File: /Users/.../X.svelte:203:8
[vite]   201|
[vite]   202|      div {
[vite]   203|          display: flex;
[vite]      |          ^
```
```


### System Info

```shell
"svelte": "5.0.0-next.133"
        "@sveltejs/vite-plugin-svelte": "^3.1.0",
node 22, macos.
```

**Comment by dominikg** [comment]
please provite a link to a reproduction repo. For scss, you need to add a preprocessor (vitePreprocess or sveltePreprocss) in your svelte config, the repls don't support it.

**Comment by shadow-identity** [comment]
I got it. I removed the preprocessor because Rich told me ["if you use typescript, feel free to remove [preprocessor]"](https://youtu.be/xCeYmdukOKI?si=I9FnjuGtBmKrw1j5) in his latest video about Svelte 5.

With preprocessor option returned, everything works fine.

**Comment by dominikg** [comment]
vitePreprocess in vite-plugin-svelte@4 (currently in prerelease) will no longer process script lang=ts by default, so it is safe to add for scss only
