### ISSUE TITLE
Template fails to run with `Named export 'svelteInspector' not found.`

### ISSUE THREAD

**Issue by Curstantine** [sveltejs/vite-plugin-svelte#922]
### Describe the bug

Whenever creating project with `pnpm create vite <name>` and `svelte` or `svelte-ts` as its template, the project fails to run returning an import resolution error.

I could not reproduce this issue with pnpm@8.x.x and node LTS.

### Reproduction URL

https://github.com/Curstantine/vite-svelte-pnpm-import-error

### Reproduction

1. Run `pnpm create vite <name> --template svelte` or `pnpm create vite <name> --template svelte-ts`
2. Install dependencies with `pnpm i`
3. Start the development server with `pnpm dev`

### Logs

```pwsh
DESKTOP-OK3DPAC@Curstantine ~/Code/Experimental/vite-deprecation-notice> $env:DEBUG="vite:*"
DESKTOP-OK3DPAC@Curstantine ~/Code/Experimental/vite-deprecation-notice> pnpm dev

> vite-deprecation-notice@0.0.0 dev C:\Users\Curstantine\Code\Experimental\vite-deprecation-notice
> vite

failed to load config from C:\Users\Curstantine\Code\Experimental\vite-deprecation-notice\vite.config.js
error when starting dev server:
file:///C:/Users/Curstantine/Code/Experimental/vite-deprecation-notice/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@3.1.0_svelte@4.2.17_vite@5.2.11/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:3
import { svelteInspector } from '@sveltejs/vite-plugin-svelte-inspector';
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'svelteInspector' not found. The requested module '@sveltejs/vite-plugin-svelte-inspector' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@sveltejs/vite-plugin-svelte-inspector';
const { svelteInspector } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:171:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:254:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)
    at async loadConfigFromBundledFile (file:///C:/Users/Curstantine/Code/Experimental/vite-deprecation-notice/node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68705:21)
    at async loadConfigFromFile (file:///C:/Users/Curstantine/Code/Experimental/vite-deprecation-notice/node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68558:28)
    at async resolveConfig (file:///C:/Users/Curstantine/Code/Experimental/vite-deprecation-notice/node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68161:28)
    at async _createServer (file:///C:/Users/Curstantine/Code/Experimental/vite-deprecation-notice/node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:64686:20)
    at async CAC.<anonymous> (file:///C:/Users/Curstantine/Code/Experimental/vite-deprecation-notice/node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/cli.js:762:24)
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 8.96 GB / 15.89 GB
  Binaries:
    Node: 22.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.3 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.67)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^3.0.2 => 3.1.0
    svelte: ^4.2.12 => 4.2.17
    vite: ^5.2.0 => 5.2.11
```

**Comment by Curstantine** [comment]
I let corepack manage the package manager versions. So `corepack up` could update the pnpm version.

I'll check again without depending on corepack and update.

**Comment by dominikg** [comment]
can't reproduce this with pnpm@9.1.3 both in stackblitz and locally the inspector works.

(in stackblitz you have to run it via `pnpm dlx pnpm@9 install`  as the globally available pnpm is still v8)

https://stackblitz.com/edit/github-r3aqwh?file=svelte.config.js,pnpm-lock.yaml

enabled inspector and it works without a hitch. Doing a local `pnpm create vite@latest --template svelte` results in an identical pnpm-lock.yml as in your reproduction repo and svelte inspector also just works.

please run `pnpm -v` and `pnm vite --version` to ensure that they are what you think they are. It might also help to delete node_modules or even the pnpm cache.

Looks like you are using windows, have you tried different shells (cmd, powershell, gitbash?)  or WSL to see if it also occurs there?

**Comment by Curstantine** [comment]
- `pnpm vite --version`: vite/5.2.11 win32-x64 node-v22.2.0
- `pnpm --version`: 9.1.3

I tried both CMD and pwsh to no avail. It's weird because I have another project that depends on `sveltejs/vite-plugin-svelte` and it works fine (in both `v3.0.2` and `v3.1.0`)

**Comment by dominikg** [comment]
hmm, i'm running out of ideas. Is there any .npmrc or another file outside of the project root that could influence this? what happens when you use `"packageManager":"pnpm@9.1.3"`  instead of the one with the version hash?

**Comment by Curstantine** [comment]
The package hash doesn't seem to make any difference.
I went through the working repository and matched the lockfiles, but I can't find a difference with either of them.

I tried removing the lockfile, deleting the node_modules, creating a pnpm workspace like in my working repository and re-installing with `pnpm i --force` to re-invalidate the lib caches. The error is still the same.

I'll do a little bit more digging around :)

**Comment by Curstantine** [comment]
Ok, I managed to get it to work by degrading the pnpm version by `corepack use pnpm@8.x` (which already worked) and upgrading back with `corepack use pnpm@9.x` which again installed `pnpm@9.1.3`, but this time working without an issue.

Yes, it magically resolved the import correctly:

![image](https://github.com/sveltejs/vite-plugin-svelte/assets/69104500/d0beb2a4-a05d-45b9-b848-a0e8ae17ae46)


Sorry for this >_>
