### ISSUE TITLE
vitePreprocess transforms things in Svelte-5-incompatible ways

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/vite-plugin-svelte#937]
### Describe the bug

Not exactly sure where to report this but this feels like as good a place as any — `vitePreprocess` takes input like this...

```svelte
<div class="warn">a</div>
<div class="warn">b</div>
<div class="error">c</div>

<style>
  .warn,
  .error {
    border-style: solid none;

    & + :global(&) {
      border-top: none;
    }
  }
</style>
```

...and transforms it in such a way that I get this error:

> Nesting selectors can only be used inside a rule

Similarly, this...

```svelte
<div class="container"></div>

<style>
  .container :global {
    .foo {
      color: red;
    }
  }
</style>
```

yields this error:

> :global(...) can be at the start or end of a selector sequence, but not in the middle

Guessing it's something to do with PostCSS? Only workaround seems to be to disable `vitePreprocess`.

### Reproduction URL

eek

### Reproduction

Maddeningly, I can't reproduce it outside my project, but will keep trying

### System Info

```shell
next
```

**Comment by dominikg** [comment]
we could investigate switching to lightningcss by default.

does it happen with sveltePreprocess too?

**Comment by dominikg** [comment]
and/or is there a config for postcss that tells it to leave nesting alone?

**Comment by bluwy** [comment]
I'm able to reproduce this only using lightningcss. Are you sure you're not using lightningcss?

With `lightningcss` installed and this vite config:

```js
	css: {
		transformer: 'lightningcss',
	}
```

I'm able to reproduce the same error message of your two examples. From what I can tell, `lightningcss` is having trouble parsing it. (Either that, or postcss is parsing it in a non-standard way)

**Comment by itsmikesharescode** [comment]
This is happening in me its so weird it deletes the class when it gets hydrated

**Comment by dominikg** [comment]
supposedly fixed in svelte according to @dummdidumm , even if not it's not on vite-plugin-sveltes vitePreprocess that is just a thin wrapper over vites postcss. *if* that transforms something in an invalid way, then we'd have to see it with vite or possibly postcss itself

**Comment by dummdidumm** [comment]
To clarify, I said that it's possibly fixed and knowing what the preprocessed output is would help answer that question. That said, if the transformer Outputs compliant code then the Svelte css parser should be able to handle it
