### ISSUE TITLE
Invalid link in vite-plugin-svelte warning

### ISSUE THREAD

**Issue by memark** [sveltejs/vite-plugin-svelte#958]
### Describe the bug

When running my app, I get the following

```
18:56:13 [vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.

...

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.
```

Following [that link](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve) I get a webpage with no mention of or solution to the actual problem. It would seem this section has been removed from the FAQ.

### Reproduction URL

n/a

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 21.05 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nodenv/versions/20.15.0/bin/node
    Yarn: 1.22.22 - ~/.nodenv/versions/20.15.0/bin/yarn
    npm: 10.7.0 - ~/.nodenv/versions/20.15.0/bin/npm
    pnpm: 9.4.0 - ~/.nodenv/versions/20.15.0/bin/pnpm
  Browsers:
    Brave Browser: 125.1.66.115
    Chrome: 127.0.6533.100
    Safari: 17.6
```

**Comment by Conduitry** [comment]
I believe https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition is the URL this should be pointing to.

**Comment by dominikg** [comment]
this warning was used by v2 of vite plugin svelte, you can still see it here https://github.com/sveltejs/vite-plugin-svelte/blob/v2/docs/faq.md#conflicts-in-svelte-resolve

**Comment by dominikg** [comment]
I think that this warning has run its course and users are encouraged to update to v-p-s 3.  If you feel strongly about that link working, you could send a PR to the current readme using the same headline (so the anchor link works) and then in the paragraph put a link to the v2 readme, explaining that this was for an older version of v-p-s

But in general i recommend updating your project to use the latest version of v-p-s
