### ISSUE TITLE
TS enums no longer get transpiled as expected starting with `vite-plugin-svelte@4.0.0-next.0` in `*.svelte` files

### ISSUE THREAD

**Issue by ndom91** [sveltejs/vite-plugin-svelte#961]
### Describe the bug

We have a component which uses an `enum` as a value in a `.svelte` file. When using `@sveltejs/vite-plugin-svelte@3.1.1` the following works as expected. However, when upgrading to `@sveltejs/vite-plugin-svelte@4.0.0-next.0`, we begin seeing errors about `ReferenceError: Can't find variable: Action`

```svelte
<script lang="ts">
	enum Action {
		Create = 'createPr',
		CreateDraft = 'createDraftPr'
	}

	const actions = Object.values(Action);
	const labels = {
		[Action.Create]: 'Create PR',
		[Action.CreateDraft]: 'Create Draft PR'
	};
  ...
```

In `3.1.1` the code above produced compiled output like this:

```js
var Action = /* @__PURE__ */
((Action2) => {
    Action2["Create"] = "createPr";
    Action2["CreateDraft"] = "createDraftPr";
    return Action2;
})(Action || {});
```

Whereas in `4.0.0-next.0` that output is missing entirely. This seems to only be effecting enums in .svelte files. Enums used like this in .ts files are unaffected.

### Reproduction URL

https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAA1WQwWrDMAyGX8WIQVoWuu2aNoWy3Rd6rXtwPWV4c-Rgy4UR8u7Ddrt2B2NL-iV9_ifojcUAzWECUgNCA7txhBr4Z0xBOKNlhBqCi16nzCZob0YWVtFnK4GDhK0kyUhxEDvNxpGYUkLyq0fFKFpR6fzqfFXfV9686vlWzmHnqySZJaVLOwosVJ4aRCveT1-oeXVWNmJYlG3L9U1p1QltEl4IDkWyKvuOjaguTN3-ivJfkhnudAWx2xeovCkdiyy0i5ToHwIrxsVz5iDJfaTigiHtcUDixfLKU3oeW_Gyvvxy81T8TB7S5hSZHQlH2hr93U5_I-bscc6GRkx5Tu4uHVuoYXAfpjf4AQ37iPNx_gWxO40x3AEAAA==

### Reproduction

In the above svelte-5 playground URL, you can see that the `enum Action` also results in the error "Action is not defined".

This [link](https://github.com/gitbutlerapp/gitbutler/pull/4697/files#diff-398ee868fe96be1ba0d4eba4344475f241b21a3b39979d43cf4616d5d97680f8) leads to a PR of our project where I bumped the dependencies and moved the `enum Action` down from the `<script lang="ts" context="module">` to the normal `<script />` tag because the enum was no longer being imported from anywhere and it's simpler that way. The PR also includes bumping a few Svelte related packages, except the `vite-plugin-svelte`, because that was giving us troubles.

### System Info

```shell
System:
  OS: Linux 6.10 NixOS 24.05 (Uakari) 24.05 (Uakari)
  CPU: (14) x64 Intel(R) Core(TM) Ultra 7 155U
  Memory: 16.20 GB / 30.87 GB
  Container: Yes
  Shell: 5.2.26 - /run/current-system/sw/bin/bash
Binaries:
  Node: 20.14.0 - /nix/store/ilkfhnqz4xczrliqjva8770x2svbfznd-nodejs-20.14.0/bin/node
  npm: 10.7.0 - /nix/store/ilkfhnqz4xczrliqjva8770x2svbfznd-nodejs-20.14.0/bin/npm
  pnpm: 9.5.0 - /nix/store/zw38hg36phakmnk3lxglyzvjwf2pivsa-corepack-nodejs-20.14.0/bin/pnpm
  bun: 1.1.20 - /run/current-system/sw/bin/bun
Browsers:
  Chromium: 127.0.6533.88
```

**Comment by dominikg** [comment]
svelte5 understands ts syntax in .svelte files without needing a preprocessor, however it does not work with typescript features that have code output. for that to work you have to change `vitePreprocess()` to  `vitePreprocess({script: true})` in svelte.config.js

**Comment by ndom91** [comment]
Ah okay, I'm curious why that's the default? :thinking: 

But thanks for the quick response!

**Comment by dominikg** [comment]
> Ah okay, I'm curious why that's the default? 🤔
> 
> But thanks for the quick response!

we might reevaluate that default. in general i think most users/components don't need this feature so it would save processing time. But it is kind of opaque and the current feedback isn't great as you already experienced. 

Would you be less concerned about this default if a message told you about it?

**Comment by ndom91** [comment]
Yeah maybe svelte-check could warn if `enum`'s or similar are used in `.svelte` files :thinking: It'd definitely save folks some headache tryign to figure out what's going on

**Comment by frederikhors** [comment]
@dominikg this should be handled with an error at compile time or it will errors on runtime only as in my case.

Plus, I think the default should be changed to handle this by default if I use Typescript.

**Comment by frederikhors** [comment]
Can you please re-open this, @ndom91?

**Comment by ndom91** [comment]
> Can you please re-open this, @ndom91?

Sure, happy to discuss

**Comment by dominikg** [comment]
forcing an extra unneeded transpile on all users just because some users use enums or other code generating features of typescript in some files is not great.

Ideally we find a way to avoid this scenario. For the record the breaking changes of 4.0 do mention that scripts are no longer preprocessed for typescript by default

> disable script preprocessing in vitePreprocess() by default because Svelte 5 supports lang=ts out of the box (https://github.com/sveltejs/vite-plugin-svelte/pull/892)

So this might also just be something that needs better communication / warnings.

There's also the question of how useful enums in .svelte script blocks are. Another way of avoiding this problem is putting them in .ts files and import.

**Comment by frederikhors** [comment]
This is not an issue with enums only, with the below code:

```svelte
<script lang="ts">
    // ...

    $effect(() => {
        // ...

        if (input) {
            input.value = someOne || someTwo;
        }
    });
</script>
```

I get:

```
Unexpected token

If you expect this syntax to work, here are some suggestions: 
If you use typescript with `svelte-preprocess`, did you add `lang="ts"` to your `script` tag? 
Did you setup a `svelte.config.js`? 
See https://github.com/sveltejs/language-tools/tree/master/docs#using-with-preprocessors for more info.svelte(js_parse_error)
```

with `someTwo` highlighted in red in my IDE.

Or this other code:

```svelte
<script lang="ts">
    const options: Partial<BaseOptions> = {
        // ...
        onReady() {
            //...
        } // <-- here the red error
    };
</script>
```

the error:

```
Unexpected token `}`. Did you mean `&rbrace;` or `{"}"}`?

If you expect this syntax to work, here are some suggestions: 
If you use typescript with `svelte-preprocess`, did you add `lang="ts"` to your `script` tag? 
Did you setup a `svelte.config.js`? 
See https://github.com/sveltejs/language-tools/tree/master/docs#using-with-preprocessors for more info.svelte(js_parse_error)
```

So now I think we should decide if Svelte 5 can handle typescript or not alone or am I wrong?

**Comment by frederikhors** [comment]
So I think the second sentence here is false:

![image](https://github.com/user-attachments/assets/58b3d48d-257c-4992-a892-4d68add2e163)

**Comment by smart** [comment]
Just upgraded to 4 and ran into this issue. Took a while to debug with the error messages only being something like expected "{" but got ";", I think the issue was I didn't even know it was enum related until digging deep into the codebase. enabled script: true and it works fine.

**Comment by dominikg** [comment]
vite-plugin-svelte@4 is going to continue to keep script: false as the default. Documentation will be updated to reflect this. svelte itself is going to get better messages to let users know that these features require a preprocessor, which v-p-s can then pick up to suggest enabling script. see https://github.com/sveltejs/svelte/commit/194570dc70d38fac14991befa09191c6c858f7a0

In general i would recommend not to put ts code that uses these in .svelte files, instead put them into .ts files and import it into .svelte files.

**Comment by dominikg** [comment]
docs update https://github.com/sveltejs/vite-plugin-svelte/pull/974

**Comment by raythurnvoid** [comment]
The current message says

> TypeScript language features like enums are not natively supported, and their use is generally discouraged. Outside of `<script>` tags, these features are not supported. For use within `<script>` tags, you will need to use a preprocessor to convert it to JavaScript before it gets passed to the Svelte compiler. If you are using `vitePreprocess`, make sure to specifically enable preprocessing script tags (`vitePreprocess({ script: true })`)|

Is there any reason why they are discouraged? I'm not aware that the Typescript team is discouraging them at all.

**Comment by dominikg** [comment]
please use our [discord](https://svelte.dev/chat)) `#help-svelte-and-kit`  or https://github.com/sveltejs/svelte/discussions for questions about sveltes typescript support. vite-plugin-svelte is only the messenger here.
